possible fixes for korean series links

diff --git a/advance b/advance
--- a/advance
+++ b/advance
@@ -27,22 +27,33 @@ PARSE(){
     fi
     D=1
     while true; do
-        if [ $D -gt 9 ]; then TAG="s$D"; else TAG="S0$D"; fi
-        if ! grep -qi "$TAG" $JUNK/"$OUTPUT.links"; then
+        if [ $D -gt 9 ]; then TAG="s$D"; TAGG="e$D"; else TAG="S0$D"; TAGG="e0$D"; fi
+        if ! grep -qiE "($TAG|$TAGG)" $JUNK/"$OUTPUT.links"; then
             if [ ! -e $JUNK/"$OUTPUT.link" ]; then
                 if [ $D == 10 ]; then unset CHECK; rm $JUNK/"$OUTPUT.links"; return; else D=$((D+1)); continue; fi
             else
                 break
             fi
         fi
-        if ! grep -qi "Season $D" $JUNK/"$OUTPUT.link" 2> /dev/null; then echo -e "\\n<h5>Season $D</h5>" >> $JUNK/"$OUTPUT.link"; fi
-        for PXL in "${PXLS[@]}"; do
-            grep -i "$TAG" $JUNK/"$OUTPUT.links" | grep -vE '(480|720|1080|2160)p' >> $JUNK/"$OUTPUT.link" || true
-            grep -ivE "$TAG.*($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -qiE "$TAG.*($PXL|${PXL}p)" && echo -e "\\n${PXL}p\\n$(grep -ivE "$TAG.*($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -iE "$TAG.*($PXL|${PXL}p)")" >> $JUNK/"$OUTPUT.link" || true
-            grep -qiE "$TAG.*($PXL|${PXL}p).*x264" $JUNK/"$OUTPUT.links" && echo -e "\\n${PXL}p x264\\n$(grep -iE "$TAG.*($PXL|${PXL}p).*x264" $JUNK/"$OUTPUT.links")" >> $JUNK/"$OUTPUT.link" || true
-            grep -qiE "$TAG.*($PXL|${PXL}p).*x265" $JUNK/"$OUTPUT.links" && echo -e "\\n${PXL}p x265\\n$(grep -iE "$TAG.*($PXL|${PXL}p).*x265" $JUNK/"$OUTPUT.links")" >> $JUNK/"$OUTPUT.link" || true
-            continue
-        done
+        if grep -qi 'korean' <<< "$OUTPUT"; then
+            echo -e "" >> $JUNK/"$OUTPUT.link"
+            for PXL in "${PXLS[@]}"; do
+                grep -i "$TAGG" $JUNK/"$OUTPUT.links" | grep -vE '(360|480|540|720|1080|2160)p' >> $JUNK/"$OUTPUT.link" || true
+                grep -ivE "$TAGG.*($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -qiE "$TAGG.*($PXL|${PXL}p)" && echo -e "$(grep -ivE "$TAGG.*($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -iE "$TAGG.*($PXL|${PXL}p)")" >> $JUNK/"$OUTPUT.link" || true
+                #grep -qiE "$TAGG.*($PXL|${PXL}p).*x264" $JUNK/"$OUTPUT.links" && echo -e "$(grep -iE "$TAGG.*($PXL|${PXL}p).*x264" $JUNK/"$OUTPUT.links")" >> $JUNK/"$OUTPUT.link" || true
+                #grep -qiE "$TAGG.*($PXL|${PXL}p).*x265" $JUNK/"$OUTPUT.links" && echo -e "$(grep -iE "$TAGG.*($PXL|${PXL}p).*x265" $JUNK/"$OUTPUT.links")" >> $JUNK/"$OUTPUT.link" || true
+                continue
+            done
+        else
+            if ! grep -qi "Season $D" $JUNK/"$OUTPUT.link" 2> /dev/null; then echo -e "\\n<h5>Season $D</h5>" >> $JUNK/"$OUTPUT.link"; fi
+            for PXL in "${PXLS[@]}"; do
+                grep -i "$TAG" $JUNK/"$OUTPUT.links" | grep -vE '(360|480|540|720|1080|2160)p' >> $JUNK/"$OUTPUT.link" || true
+                grep -ivE "$TAG.*($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -qiE "$TAG.*($PXL|${PXL}p)" && echo -e "\\n${PXL}p\\n$(grep -ivE "$TAG.*($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -iE "$TAG.*($PXL|${PXL}p)")" >> $JUNK/"$OUTPUT.link" || true
+                grep -qiE "$TAG.*($PXL|${PXL}p).*x264" $JUNK/"$OUTPUT.links" && echo -e "\\n${PXL}p x264\\n$(grep -iE "$TAG.*($PXL|${PXL}p).*x264" $JUNK/"$OUTPUT.links")" >> $JUNK/"$OUTPUT.link" || true
+                grep -qiE "$TAG.*($PXL|${PXL}p).*x265" $JUNK/"$OUTPUT.links" && echo -e "\\n${PXL}p x265\\n$(grep -iE "$TAG.*($PXL|${PXL}p).*x265" $JUNK/"$OUTPUT.links")" >> $JUNK/"$OUTPUT.link" || true
+                continue
+            done
+        fi
         D=$((D+1))
     done
     mv $JUNK/"$OUTPUT.link" $JUNK/"$OUTPUT.links")
@@ -60,7 +71,7 @@ CROSS_CHECK(){  ###fix
             if grep -q 'http' $JUNK/"$OUTPUT.wp_links"; then
                 grep -o '<a.*http.*a>' $JUNK/"$OUTPUT.links" | sort -n > $JUNK/"$OUTPUT.dl" && sort -n $JUNK/"$OUTPUT.wp_links" > $JUNK/"$OUTPUT.wp"
                 if cmp $JUNK/"$OUTPUT.wp" $JUNK/"$OUTPUT.dl"; then
-                    echo 'no need to update'; sig_abort 1; return 1
+                    echo 'no need to update'; sig_abort 1
                 else
                     if [ "$USER" == "$SERVER" ]; then
                         if ! grep -q -- "--test" <<< "$@"; then DELETE_WP_POST; fi; echo "deleted $OUTPUT"
@@ -83,10 +94,10 @@ FUNC(){
     set -xe; echo -e "\\n${OUTPUT}${TASKS}\\n-----------------------"
     if grep -q "$OUTPUT" <<< $BLACKLIST; then echo "$OUTPUT -- blacklisted"; return 1; fi #blaclist if title is in blacklist file
     curl $ARGS $(grep "$OUTPUT" "$JUNK/main" | grep -o http.*html) > "$JUNK/$OUTPUT.site" || exit #download series page
-    grep -oiE "<a href=.*(S[0-9][0-9]E[0-9][0-9]).*(mkv|mp4|avi).*</a>" "$JUNK/$OUTPUT.site" | sed 's:(twitchdl.com)::;s:</a>:(turbodl.xyz)</a>:g; /imdb/d; s:<br />:\n:g; s:" .*">::g;' > "$JUNK/$OUTPUT.links"
+    grep -oiE "<a href=.*(S[0-9][0-9]E[0-9][0-9]|E[0-9][0-9]).*(mkv|mp4|avi).*</a>" "$JUNK/$OUTPUT.site" | sed 's:(twitchdl.com)::;s:</a>:(turbodl.xyz)</a>:g; /imdb/d; s:<br />:\n:g; s:" .*">::g;' > "$JUNK/$OUTPUT.links"
     sed -i '/subtitle/d; s:<.*span.*span>::g; /^<span/d' "$JUNK/$OUTPUT.links" #get links and remove junk from links & add 'turbodl.xyz' to the end of links without it
     grep -q 'http' $JUNK/"$OUTPUT.links" && CHECK=1
-    NAME=$(sed "s: -.*Season.*::" <<< "$OUTPUT")
+    NAME=$(sed "s: -.*Season.*::; s: (Korean Series)::; s: (Anime)::" <<< "$OUTPUT")
     grep -q "$OUTPUT=" <<< $WHITELIST && NAME=$(sed "/$OUTPUT/!d; s/.*$OUTPUT=//; s/\".*//")
     TMDB_API=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/search/tv?api_key=0dec8436bb1b7de2bbcb1920ac31111f&query=$(sed "s/ /%20/g" <<< "$NAME")&page=1&" || exit)
     if [ $(jq '.total_results' <<< "$TMDB_API") == 0 ]; then echo "$OUTPUT -- not found" >> stoday.txt; return 1; fi
@@ -123,7 +134,7 @@ FUNC(){
     fi; exit) &
     set -xe
     IMDB_ID=$(curl $ARGS --header "Content-Type: application/json" --header "trakt-api-version: 2" --header "trakt-api-key: 64ba02e985f18ec3a00186209b3605cfbbeedf9890898e3a06b8e020111e8194" "https://api.trakt.tv/search/tmdb/$TMDB_ID?type=show" | jq -r ".[0].show.ids.imdb")
-    ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT -- false trakt API response" >> stoday.txt && return 1
+    ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT -- false trakt API response" >> stoday.txt && sig_abort 1
     (exec 3>&1 4>&2; trap 'exec 2>&4 1>&3' 0 1 2 3; exec 1>"logs/${OUTPUT}_eztv.log" 2>&1
     declare -a PID; I=1; J=100; A=0
     while true; do
@@ -189,7 +200,11 @@ set -xe
         if [ ! $CHECK ]; then
             echo "$OUTPUT -- not published :no links or magnets" >> stoday.txt; sig_abort 1
         else
-            STATUS="with only links"
+            if [ -e $JUNK/"$OUTPUT.links" ]; then
+                STATUS="with only links"
+            else
+                echo "$OUTPUT -- not published :no links or magnets" >> stoday.txt; sig_abort 1
+            fi
         fi
     fi
     curl $ARGS "$POSTER" -o "series/$TITLE".jpg
@@ -214,7 +229,7 @@ set -xe
 trap sig_abort SIGINT
 start=`date +%s`
 ARGS='--connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -ks'; SERVER="root"; LOCAL="persie"
-DIR=~/.turbodl; PXLS=(480 720 1080 2160);
+DIR=~/.turbodl; PXLS=(360 480 540 720 1080 2160);
 mkdir -p $DIR/movies $DIR/series $DIR/logs $DIR/junk; cd "$DIR"; JUNK=junk
 find . ! -name '*list' ! -name 'md5' -type f -exec rm -rf {} +
 if [ "$USER" == "$SERVER" ]; then cat ~/turbodl/list > $DIR/list; else cat ~/git/turbodl/list > $DIR/list; fi
