adding torrents

diff --git a/advance b/advance
--- a/advance
+++ b/advance
@@ -1,19 +1,14 @@
 #!/bin/env bash
 set -e
-PARSE(){
-#set +xe
-    curl $ARGS --header "Content-Type: application/json" "https://eztv.io/api/get-torrents?imdb_id=$(sed 's:tt::' <<< $IMDB_ID)&limit=100" | jq . > "$JUNK/$OUTPUT.tor"
-    if [ $(jq '.torrents_count' $JUNK/"$OUTPUT.tor") == 0 ]; then
-        rm $JUNK/"$OUTPUT.tor"
+FINALIZE(){
+    if [ "$KEY" ]; then
+        echo -e "<p style=\"text-align: center;\">\\n$PLOT\\n\\n<center>Trailer:\\n<iframe src=\"https://www.youtube.com/embed/$KEY?modestbranding=1&showinfo=0&rel=0&iv_load_policy=3&color=white&controls=0\" width=\"500\" height=\"300\" frameborder=\"0\"></iframe></centre></p>\\n\\n<p style=\"text-align: center;\">IMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE</p>\\n\\n<div style=\"text-align: center;\">Download Links:\\n$(cat $JUNK/"$OUTPUT.links")\\n</div>\\n\\n<p style=\"text-align: center;\">\\n\\n\\nLinks not downloading?\\nSome N/A links don't work, don't be surprised. Also some servers do not permit simultaneous downloads above 2 or 3, finish the current download and try again.\\nOr better yet, take a look at our <a href=\"https://turbodl.xyz/tutorials/\" target=\"_blank\" rel=\"nofollow\">Tutorials</a> on how to download effectively.\\nPlease leave a us reply below or contact us via <a href=\"https://chat.whatsapp.com/DjmtHlPvrFUFgbMCseVm3Y\" target=\"_blank\" rel=\"nofollow\">Whatsapp</a> or <a href=\"https://t.me/turbodl\" target=\"_blank\" rel=\"nofollow\">Telegram</a> if links are not working or if you have an issue or suggestion.\\n\\n<h3>Thank you for using TurboDL</h3></p>\\n\\nTags: $GENRE, $Y" > series/"$OUTPUT".txt
     else
-        A=0
-        while [ $A != $(jq -r '.torrents | length' $JUNK/"$OUTPUT.tor") ]; do
-            echo "<a href=$(jq ".torrents | .[$A].magnet_url" $JUNK/"$OUTPUT.tor")>$(jq -r ".torrents | .[$A].title" $JUNK/"$OUTPUT.tor") [torrent] (turbodl.xyz)</a> - $(($(jq -r ".torrents | .[$A].size_bytes" $JUNK/"$OUTPUT.tor") / 2**20))MB" >> test
-            A=$((A+1))
-        done
+        echo -e "<p style=\"text-align: center;\">\\n$PLOT</p>\\n\\n<p style=\"text-align: center;\">IMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE</p>\\n\\n<div style=\"text-align: center;\">Download Links:\\n$(cat $JUNK/"$OUTPUT.links")\\n</div><div style=\"text-align: center;\">\\n\\n\\nLinks not downloading?\\nSome N/A links don't work, don't be surprised. Also some servers do not permit simultaneous downloads above 2 or 3, finish the current download and try again.\\nOr better yet, take a look at our <a href=\"https://turbodl.xyz/tutorials/\" target=\"_blank\" rel=\"nofollow\">Tutorials</a> on how to download effectively.\\nPlease leave a us reply below or contact us via <a href=\"https://chat.whatsapp.com/DjmtHlPvrFUFgbMCseVm3Y\" target=\"_blank\" rel=\"nofollow\">Whatsapp</a> or <a href=\"https://t.me/turbodl\" target=\"_blank\" rel=\"nofollow\">Telegram</a> if links are not working or if you have an issue or suggestion.\\n\\n<h3>Thank you for using TurboDL</h3></div>\\n\\nTags: $GENRE, $Y" > series/"$OUTPUT".txt
     fi
-    exit
-#    ) &
+}
+PARSE(){
+    (exec 3>&1 4>&2; trap 'exec 2>&4 1>&3' 0 1 2 3; exec 1>"logs/${OUTPUT}_parse.log" 2>&1
     if [ "$USER" == "$SERVER" ]; then
         while IFS= read -r "LINE"; do
             if ! grep -q 'http' <<< $LINE; then continue; fi
@@ -22,11 +17,17 @@ PARSE(){
         done < $JUNK/"$OUTPUT.links"
         mv $JUNK/"$OUTPUT.links2" $JUNK/"$OUTPUT.links"
     fi
-    touch $JUNK/"$OUTPUT.link"; D=1
+    D=1
     while true; do
         if [ $D -gt 9 ]; then TAG="s$D"; else TAG="S0$D"; fi
-        if ! grep -qi "$TAG" $JUNK/"$OUTPUT.links"; then break; fi
-        if ! grep -qi "Season $D" $JUNK/"$OUTPUT.link"; then echo -e "\\n<h3>Season $D</h3>" >> $JUNK/"$OUTPUT.link"; fi
+        if ! grep -qi "$TAG" $JUNK/"$OUTPUT.links"; then
+            if [ ! -e $JUNK/"$OUTPUT.link" ]; then
+                if [ $D == 10 ]; then echo 'links missing'; rm $JUNK/"$OUTPUT.link*"; return; else D=$((D+1)); continue; fi
+            else
+                break
+            fi
+        fi
+        if ! grep -qi "Season $D" $JUNK/"$OUTPUT.link" 2> /dev/null; then echo -e "\\n<h3>Season $D</h3>" >> $JUNK/"$OUTPUT.link"; fi
         for PIXEL in "${PIXELS[@]}"; do
             grep -i "$TAG" $JUNK/"$OUTPUT.links" | grep -vE '(480|720|1080|2160)p' >> $JUNK/"$OUTPUT.link" || true
             grep -ivE "$TAG.*($PIXEL|${PIXEL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -qiE "$TAG.*($PIXEL|${PIXEL}p)" && echo -e "\\n${PIXEL}p\\n$(grep -ivE "$TAG.*($PIXEL|${PIXEL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -iE "$TAG.*($PIXEL|${PIXEL}p)")" >> $JUNK/"$OUTPUT.link" || true
@@ -36,9 +37,7 @@ PARSE(){
         done
         D=$((D+1))
     done
-    mv $JUNK/"$OUTPUT.link" $JUNK/"$OUTPUT.links"
-exit
-set -xe
+    mv $JUNK/"$OUTPUT.link" $JUNK/"$OUTPUT.links")
 }
 CROSS_CHECK(){
     DELETE_WP_POST(){
@@ -72,53 +71,118 @@ FUNC(){
     exec 3>&1 4>&2; trap 'exec 2>&4 1>&3' 0 1 2 3; exec 1>"logs/$OUTPUT.log" 2>&1
     unset NAME TMDB_API POSTER TMDB_ID TRAILERS KEY IMDB_ID OMDB_API TITLE CAST GENRE RATING PLOT SAME TYPE
     set -xe; echo -e "\\n${OUTPUT}${TASKS}\\n-----------------------"
-    if grep -q "$OUTPUT" <<< $BLACKLIST; then echo "$OUTPUT -- blacklisted" >> stoday.txt; return; fi #blaclist if title is in blacklist file
+    if grep -q "$OUTPUT" <<< $BLACKLIST; then echo "$OUTPUT -- blacklisted" >> stoday.txt; return 1; fi #blaclist if title is in blacklist file
     curl $ARGS $(grep "$OUTPUT" "$JUNK/main" | grep -o http.*html) > "$JUNK/$OUTPUT.site" || exit #download series page
     grep -oiE "<a href=.*(S[0-9][0-9]E[0-9][0-9]).*(mkv|mp4|avi).*</a>" "$JUNK/$OUTPUT.site" | sed 's:(twitchdl.com)::;s:</a>:(turbodl.xyz)</a>:g; /imdb/d; s:<br />:\n:g; s:" .*">::g;' > "$JUNK/$OUTPUT.links"
     sed -i '/subtitle/d; s:<.*span.*span>::g; /^<span/d' "$JUNK/$OUTPUT.links" #get links and remove junk from links & add 'turbodl.xyz' to the end of links without it
-    [ -z "$JUNK/$OUTPUT.links" ] && echo "$OUTPUT -- no links" >> stoday.txt && continue || grep -qE "(hd.*cm|HDCAM|HDCam|CAM|HDTS|HDTC|DVD|dvd|SCR|Scr|scr).*(mkv|mp4|avi)" "$JUNK/$OUTPUT.links" && echo '$OUTPUT is CAM' && continue #remove movies containing CAM like links
+    [ -z "$JUNK/$OUTPUT.links" ] && echo "$OUTPUT -- no links" >> stoday.txt && continue || grep -qE "(hd.*cm|HDCAM|HDCam|CAM|HDTS|HDTC|DVD|dvd|SCR|Scr|scr).*(mkv|mp4|avi)" "$JUNK/$OUTPUT.links" && echo '$OUTPUT is CAM' && return 1 #remove movies containing CAM like links
     NAME=$(sed "s: -.*Season.*::" <<< "$OUTPUT")
+    #YEAR=$(sed '0,/class=.*post-body/d; /CLICK ON.* LINK.* BELOW TO DOWNLOAD/,$d' $JUNK/"$OUTPUT.site" | grep -oE '(Release.*[0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9]<br />)' | grep -o '[0-9][0-9][0-9][0-9]' | head -1 || true)
     grep -q "$OUTPUT=" <<< $WHITELIST && NAME=$(sed "/$OUTPUT/!d; s/.*$OUTPUT=//; s/\".*//")
-    TMDB_API=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/search/tv?api_key=0dec8436bb1b7de2bbcb1920ac31111f&query=$(sed "s/ /%20/g" <<< "$NAME")&page=1" || exit)
-    if [ $(jq '.total_results' <<< "$TMDB_API") == 0 ]; then echo "$OUTPUT -- not found" >> stoday.txt; continue; fi
-    if [ $(jq -r ".results[0] | .poster_path" <<< "$TMDB_API") != 'null' ]; then
-        TMDB_ID=$(jq -r ".results[0] | .id" <<< ""$TMDB_API"")
-        POSTER="https://image.tmdb.org/t/p/w500$(jq -r ".results[0] | .poster_path" <<< "$TMDB_API")"
-    else
-        echo "$OUTPUT -- no poster" >> stoday.txt && return
-    fi
-    TRAILER(){
-        GET_TRAILER(){
-            while [ $A != $(jq '.results | length' <<< "$TRAILERS") ]; do
-                if [ $1 == "$(jq -r ".results[$A].type" <<< "$TRAILERS")" ]; then
-                    KEY=$(jq -r ".results[$A].key" <<< "$TRAILERS"); export KEY; break
-                elif [ $A == $(jq '.results | length' <<< "$TRAILERS") ]; then
-                    break
-                else
-                    A=$((A+1)); continue
-                fi
-            done
-        }
-        set +xe
-        TRAILERS=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/tv/$TMDB_ID/videos?api_key=0dec8436bb1b7de2bbcb1920ac31111f" || exit)
-        if [ "$(jq '.results | length' <<< $TRAILERS)" != '0' ]; then
-            _TYPES=(Trailer Teaser Featurette)
-            for _TYPE in "${_TYPES[@]}"; do A=0; GET_TRAILER $_TYPE; if [ $KEY ]; then break; fi; done
+    TMDB_API=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/search/tv?api_key=0dec8436bb1b7de2bbcb1920ac31111f&query=$(sed "s/ /%20/g" <<< "$NAME")&page=1&year=$YEAR" || exit)
+    if [ $(jq '.total_results' <<< "$TMDB_API") == 0 ]; then echo "$OUTPUT -- not found" >> stoday.txt; return 1; fi
+    A=0
+    while true; do
+        if [ $(jq -r ".results[$A] | .first_air_date" <<< "$TMDB_API" | sed 's:-::g') -lt 19991201 ]; then
+            A=$((A+1)); continue
+        else
+            if [ $(jq -r ".results[$A] | .poster_path" <<< "$TMDB_API") != 'null' ]; then
+                TMDB_ID=$(jq -r ".results[$A] | .id" <<< ""$TMDB_API"")
+                POSTER="https://image.tmdb.org/t/p/w500$(jq -r ".results[$A] | .poster_path" <<< "$TMDB_API")"
+                break
+            else
+                echo "$OUTPUT -- no poster" >> stoday.txt && return 1
+            fi
         fi
-        set -xe
+    done
+    (GET_TRAILER(){
+        while [ $A != $(jq '.results | length' <<< "$TRAILERS") ]; do
+            if [ $1 == "$(jq -r ".results[$A].type" <<< "$TRAILERS")" ]; then
+                KEY=$(jq -r ".results[$A].key" <<< "$TRAILERS"); export KEY; break
+            elif [ $A == $(jq '.results | length' <<< "$TRAILERS") ]; then
+                break
+            else
+                A=$((A+1)); continue
+            fi
+        done
     }
-    TRAILER &
+    set +xe
+    TRAILERS=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/tv/$TMDB_ID/videos?api_key=0dec8436bb1b7de2bbcb1920ac31111f" || exit)
+    if [ "$(jq '.results | length' <<< $TRAILERS)" != '0' ]; then
+        _TYPES=(Trailer Teaser Featurette)
+        for _TYPE in "${_TYPES[@]}"; do A=0; GET_TRAILER $_TYPE; if [ $KEY ]; then break; fi; done
+    fi) &
+    set -xe
     IMDB_ID=$(curl $ARGS --header "Content-Type: application/json" --header "trakt-api-version: 2" --header "trakt-api-key: 64ba02e985f18ec3a00186209b3605cfbbeedf9890898e3a06b8e020111e8194" "https://api.trakt.tv/search/tmdb/$TMDB_ID?type=show" | jq -r ".[0].show.ids.imdb")
-    ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT -- false trakt API response" >> stoday.txt && return
+    ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT -- false trakt API response" >> stoday.txt && return 1
+exit    #fix
+    (exec 3>&1 4>&2; trap 'exec 2>&4 1>&3' 0 1 2 3; exec 1>"logs/${OUTPUT}_eztv.log" 2>&1
+    I=1; J=100; A=0
+    while true; do
+        EZTV_API=$(curl $ARGS --header "Content-Type: application/json" "https://eztv.io/api/get-torrents?imdb_id=$(sed 's:tt::' <<< $IMDB_ID)&limit=100&page=$I") #| jq . > "$JUNK/$OUTPUT.tor"
+        (set +xe
+        while [ $A -lt $(jq -r '.torrents | length' <<< "$EZTV_API") ]; do
+            echo "<a href=$(jq ".torrents | .[$A].magnet_url" <<< "$EZTV_API")>$(jq -r ".torrents | .[$A].title" <<< "$EZTV_API") [torrent] (turbodl.xyz)</a> - $(($(jq -r ".torrents | .[$A].size_bytes" <<< "$EZTV_API") / 2**20))MB" >> "$JUNK/$OUTPUT.mg"
+            A=$((A+1))
+        done
+        set -xe) &
+        echo "$!" >> $JUNK/pid2
+        if [ $(jq '.torrents_count' <<< "$EZTV_API") -gt $J ]; then
+            I=$((I+1)); J=$((J+100)); A=0; continue
+        else
+            if [ $(jq '.torrents_count' <<< "$EZTV_API") == 0 ]; then
+                break
+            fi
+        fi
+        break
+    done
+    while grep -ow -f $JUNK/pid2 <<< $(ls /proc); do sleep 7; continue; done
+set +xe
+    while IFS= read -r "MAG"; do
+        grep -F "$MAG" $JUNK/"$OUTPUT.mg" >> $JUNK/"$OUTPUT.magnets"
+    done <<< $(grep -o ">.*" "$JUNK/$OUTPUT.mg" | sort -n)
+set -xe
+    rm $JUNK/"$OUTPUT.mg"
+    D=1
+    if [ $D -gt 9 ]; then TAG="s$D"; else TAG="S0$D"; fi
+    if ! grep -qi "$TAG" $JUNK/"$OUTPUT.magnets"; then
+        if [ ! -e $JUNK/"$OUTPUT.mg" ]; then
+            if [ $D == 10 ]; then rm $JUNK/"$OUTPUT.m*"; return; else D=$((D+1)); continue; fi
+        else
+            break
+        fi
+    fi
+    if ! grep -qi "Season $D" $JUNK/"$OUTPUT.mg" 2> /dev/null; then echo -e "\\n<h3>Season $D</h3>" >> $JUNK/"$OUTPUT.mg"; fi
+    for PIXEL in "${PIXELS[@]}"; do
+        grep -i "$TAG" $JUNK/"$OUTPUT.magnets" | grep -vE '(480|720|1080|2160)p' >> $JUNK/"$OUTPUT.mg" || true
+        grep -ivE "$TAG.*($PIXEL|${PIXEL}p).*(x264|x265)" $JUNK/"$OUTPUT.magnets" | grep -qiE "$TAG.*($PIXEL|${PIXEL}p)" && echo -e "\\n${PIXEL}p\\n$(grep -ivE "$TAG.*($PIXEL|${PIXEL}p).*(x264|x265)" $JUNK/"$OUTPUT.magnets" | grep -iE "$TAG.*($PIXEL|${PIXEL}p)")">> $JUNK/"$OUTPUT.mg" || true
+        grep -qiE "$TAG.*($PIXEL|${PIXEL}p).*x264" $JUNK/"$OUTPUT.magnets" && echo -e "\\n${PIXEL}p x264\\n$(grep -iE "$TAG.*($PIXEL|${PIXEL}p).*x264" $JUNK/"$OUTPUT.magnets")" >> $JUNK/"$OUTPUT.mg" || true
+        grep -qiE "$TAG.*($PIXEL|${PIXEL}p).*x265" $JUNK/"$OUTPUT.magnets" && echo -e "\\n${PIXEL}p x265\\n$(grep -iE "$TAG.*($PIXEL|${PIXEL}p).*x265" $JUNK/"$OUTPUT.magnets")" >> $JUNK/"$OUTPUT.mg" || true
+        continue
+    done
+    mv $JUNK/"$OUTPUT.mg" $JUNK/"$OUTPUT.magnets"
+    if [ -e $JUNK/"$OUTPUT.magnets" ]; then sed -i "1s/^/\\n\\nTorrents" $JUNK/"$OUTPUT.magnets"; fi
+    ) &
+exit
+    echo $! >> $JUNK/pid2
     OMDB_API=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?i=$IMDB_ID&plot=short&apikey=7759dbc7" || exit)
-    grep "Error getting data" <<< "$OMDB_API" && echo "$OUTPUT -- false OMDB API response" >> stoday.txt && return
+    grep "Error getting data" <<< "$OMDB_API" && echo "$OUTPUT -- false OMDB API response" >> stoday.txt && return 1
     YEAR=$(jq -r '.Year' <<< $OMDB_API); TITLE="$(jq -r ".Title" <<< "$OMDB_API") ($YEAR)"
-    CAST=$(jq -r '.Actors' <<< "$OMDB_API"); GENRE=$(jq -r '.Genre' <<< "$OMDB_API")
-    RATING=$(jq -r '.imdbRating' <<< "$OMDB_API"); PLOT=$(jq -r '.Plot' <<< "$OMDB_API")
-    grep -qiE '(documentary|reality-tv|talk-show)' <<< "$GENRE" && ! grep -q "$OUTPUT" <<< $WHITELIST && return
-    if ! grep -q "$OUTPUT" <<< $WHITELIST; then if [ "$GENRE" == 'N/A' ]; then echo "$OUTPUT -- N/A" >> stoday.txt && return; fi; fi
+    YEAR=$(sed 's/–/, /' <<< $YEAR); CAST=$(jq -r '.Actors' <<< "$OMDB_API"); GENRE=$(jq -r '.Genre' <<< "$OMDB_API"); RATING=$(jq -r '.imdbRating' <<< "$OMDB_API"); PLOT=$(jq -r '.Plot' <<< "$OMDB_API")
+    grep -qiE '(documentary|reality-tv|talk-show)' <<< "$GENRE" && ! grep -q "$OUTPUT" <<< $WHITELIST && return 1
+    if ! grep -q "$OUTPUT" <<< $WHITELIST; then if [ "$GENRE" == 'N/A' ]; then echo "$OUTPUT -- N/A" >> stoday.txt && return 1; fi; fi
     grep -owF "$TITLE" series_list && CROSS_CHECK; PARSE
-    #sed 's/–/, /'
+    if ! grep -q 'http' $JUNK/"$OUTPUT.links"; then echo "$OUTPUT -- no links" >> stoday.txt; rm $JJUNK/"$OUTPUT.links"; fi
+    curl $ARGS "$POSTER" -o "series/$TITLE".jpg
+    if [ $(identify -format "%w" "series/$TITLE.jpg")> /dev/null -gt 530 -o $(identify -format "%w" "series/$TITLE.jpg")> /dev/null -lt 470 -o $(identify -format "%h" "series/$TITLE.jpg")> /dev/null -gt 780 -o $(identify -format "%h" "series/$TITLE.jpg")> /dev/null -lt 700 ]; then
+        if ! grep -q "$OUTPUT" whitelist; then
+            echo "$OUTPUT -- image dimension error" >> stoday.txt; return 1
+        fi
+    fi
+    #fix
+    while grep -owq -f "$JUNK/pid2" <<< $(ls /proc); do sleep 7; continue; done
+    if [ -e $JUNK/"$OUTPUT.magnets" ]; then cat $JUNK/"$OUTPUT.magnets" >> $JUNK/"$OUTPUT.links"; fi
+    FINALIZE
 
 }
 start=`date +%s`
