update

diff --git a/advance b/advance
--- a/advance
+++ b/advance
@@ -1,5 +1,13 @@
 #!/bin/env bash
 set -e
+sig_abort(){
+    if [ $1 ]; then
+        xargs kill <$JUNK/"$OUTPUT.pids" 2> /dev/null
+    else
+        xargs kill <$JUNK/pids 2> /dev/null
+    fi
+    return 1
+}
 FINALIZE(){
     if [ "$KEY" ]; then
         echo -e "<p style=\"text-align: center;\">\\n$PLOT\\n\\n<center>Trailer:\\n<iframe src=\"https://www.youtube.com/embed/$KEY?modestbranding=1&showinfo=0&rel=0&iv_load_policy=3&color=white&controls=0\" width=\"500\" height=\"300\" frameborder=\"0\"></iframe></centre></p>\\n\\n<p style=\"text-align: center;\">IMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE</p>\\n\\n<div style=\"text-align: center;\"><h3>Download Links:</h3>\\n$(cat $JUNK/"$OUTPUT.links")\\n</div>\\n\\n<p style=\"text-align: center;\">\\n\\n\\nLinks not downloading?\\nSome N/A links don't work, don't be surprised. Also some servers do not permit simultaneous downloads above 2 or 3, finish the current download and try again.\\nOr better yet, take a look at our <a href=\"https://turbodl.xyz/tutorials/\" target=\"_blank\" rel=\"nofollow\">Tutorials</a> on how to download effectively.\\nPlease leave a us reply below or contact us via <a href=\"https://chat.whatsapp.com/DjmtHlPvrFUFgbMCseVm3Y\" target=\"_blank\" rel=\"nofollow\">Whatsapp</a> or <a href=\"https://t.me/turbodl\" target=\"_blank\" rel=\"nofollow\">Telegram</a> if links are not working or if you have an issue or suggestion.\\n\\n<h3>Thank you for using TurboDL</h3></p>\\n\\nTags: $GENRE, $Y" > series/"$OUTPUT".txt
@@ -41,8 +49,8 @@ PARSE(){
 }
 CROSS_CHECK(){  ###fix
     DELETE_WP_POST(){
-        curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://series.turbodl.xyz/wp-json/wp/v2/posts/$(jq ".[$A].id" $JUNK/"$OUTPUT.wp_results")" 2> /dev/null
-        curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://series.turbodl.xyz/wp-json/wp/v2/media/$(jq ".[$A].featured_media" $JUNK/"$OUTPUT.wp_results")?force=true" 2> /dev/null
+        curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://series.turbodl.xyz/wp-json/wp/v2/posts/$(jq ".[$A].id" $JUNK/"$OUTPUT.wp_results")" > /dev/null
+        curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://series.turbodl.xyz/wp-json/wp/v2/media/$(jq ".[$A].featured_media" $JUNK/"$OUTPUT.wp_results")?force=true" > /dev/null
     }
     A=0
     curl $ARGS -X GET "https://series.turbodl.xyz/wp-json/wp/v2/posts?search=$(sed 's/[(-)]//g; s/ /%20/g' <<< "$TITLE")&per_page=4" | jq . > $JUNK/"$OUTPUT.wp_results"
@@ -50,9 +58,9 @@ CROSS_CHECK(){  ###fix
         if grep "$(sed 's/ (.*)//' <<< "$TITLE")" <<< "$(jq -r ".[$A].title.rendered" $JUNK/"$OUTPUT.wp_results" | sed "s/&#8211;/-/g; s/&#8217;/'/g; s/&#038;/\&/g; s/&#8216;/'/g; s/&#822[0-1];/\"/g; s/&amp;/\&/g; s/&#8230;/\.\.\./; s/.u2013/–/; s/.u00e9/é/;")"; then
             jq -r ".[$A].content.rendered" $JUNK/"$OUTPUT.wp_results" | grep -o '<a href.*http.*</a>' | sed "s/&#8217;/'/g; s/&#8211;/-/g; s/&#8230;/\.\.\./g; /Whatsapp/d; /Telegram/d; /Tutorials/d" > $JUNK/"$OUTPUT.wp_links" || true
             if grep -q 'http' $JUNK/"$OUTPUT.wp_links"; then
-                grep -o '<a.*http.*a>' $JUNK/"$OUTPUT.links" | sort -n > $JUNK/"$OUTPUT.two" && sort -n $JUNK/"$OUTPUT.wp_links" > $JUNK/"$OUTPUT.one"
-                if cmp $JUNK/"$OUTPUT.one" $JUNK/"$OUTPUT.two"; then
-                    echo 'no need to update'; return 1
+                grep -o '<a.*http.*a>' $JUNK/"$OUTPUT.links" | sort -n > $JUNK/"$OUTPUT.dl" && sort -n $JUNK/"$OUTPUT.wp_links" > $JUNK/"$OUTPUT.wp"
+                if cmp $JUNK/"$OUTPUT.wp" $JUNK/"$OUTPUT.dl"; then
+                    echo 'no need to update'; sig_abort 1; return 1
                 else
                     if [ "$USER" == "$SERVER" ]; then DELETE_WP_POST; fi; echo "deleted $OUTPUT"
                 fi
@@ -124,7 +132,7 @@ FUNC(){
             echo "<a href=$(jq ".torrents | .[$A].magnet_url" <<< "$EZTV_API")>$(jq -r ".torrents | .[$A].title" <<< "$EZTV_API") [torrent] (turbodl.xyz)</a> - $(($(jq -r ".torrents | .[$A].size_bytes" <<< "$EZTV_API") / 2**20))MB" >> "$JUNK/$OUTPUT.mg"
             A=$((A+1))
         done; exit) &
-        PID+=($!)
+        PID+=($!); echo $! | tee -a $JUNK/pids $JUNK/"$OUTPUT.pids"
         if [ $(jq '.torrents_count' <<< "$EZTV_API") -gt $J ]; then
             I=$((I+1)); J=$((J+100)); A=0; continue
         fi
@@ -160,13 +168,15 @@ set -xe
     done
     mv $JUNK/"$OUTPUT.mg" $JUNK/"$OUTPUT.magnets"
     sed -i "1s:^:\n<h3>Magnets\:</h3>:" $JUNK/"$OUTPUT.magnets"; rm $JUNK/"$OUTPUT.site"; exit) &
+    echo $! | tee -a $JUNK/pids $JUNK/"$OUTPUT.pids"
     OMDB_API=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?i=$IMDB_ID&plot=short&apikey=7759dbc7" || exit)
-    grep "Error getting data" <<< "$OMDB_API" && echo "$OUTPUT -- false OMDB API response" >> stoday.txt && return 1
+    grep "Error getting data" <<< "$OMDB_API" && echo "$OUTPUT -- false OMDB API response" >> stoday.txt && sig_abort 1
     YEAR=$(jq -r '.Year' <<< $OMDB_API); TITLE="$(jq -r ".Title" <<< "$OMDB_API") ($YEAR)"
     YEAR=$(sed 's/–/, /' <<< $YEAR); CAST=$(jq -r '.Actors' <<< "$OMDB_API"); GENRE=$(jq -r '.Genre' <<< "$OMDB_API"); RATING=$(jq -r '.imdbRating' <<< "$OMDB_API"); PLOT=$(jq -r '.Plot' <<< "$OMDB_API")
-    grep -qiE '(documentary|reality-tv|talk-show)' <<< "$GENRE" && ! grep -q "$OUTPUT" <<< $WHITELIST && return 1
-    if ! grep -q "$OUTPUT" <<< $WHITELIST; then if [ "$GENRE" == 'N/A' ]; then echo "$OUTPUT -- N/A" >> stoday.txt && return 1; fi; fi
-    grep -owF "$TITLE" series_list && CROSS_CHECK; PARSE
+    grep -qiE '(documentary|reality-tv|talk-show)' <<< "$GENRE" && ! grep -q "$OUTPUT" <<< $WHITELIST && sig_abort 1
+    if ! grep -q "$OUTPUT" <<< $WHITELIST; then if [ "$GENRE" == 'N/A' ]; then echo "$OUTPUT -- N/A" >> stoday.txt && sig_abort 1; fi; fi
+    grep -owF "$TITLE" series_list && if [ $(($(date +%Y%m%d)-$(grep -ow "$TITLE.*" series_list | grep -o '%.*' | sed 's:%::'))) -le 3 ]; then echo "$OUTPUT -- published within 3days" >> stoday.txt; sig_abort 1; else CROSS_CHECK; fi
+    PARSE
     set +xe; while [ -e $JUNK/"$OUTPUT.site" ]; do sleep 5; continue; done; set -xe
     if [ -e $JUNK/"$OUTPUT.magnets" ]; then
         cat $JUNK/"$OUTPUT.magnets" >> $JUNK/"$OUTPUT.links"
@@ -174,7 +184,7 @@ set -xe
     else
         if [ ! $CHECK ]; then
             echo "$OUTPUT -- no links & magnets" >> stoday.txt
-            return 1
+            sig_abort 1
         else
             echo "$OUTPUT -- no magnets" >> stoday.txt
         fi
@@ -182,7 +192,7 @@ set -xe
     curl $ARGS "$POSTER" -o "series/$TITLE".jpg
     if [ $(identify -format "%w" "series/$TITLE.jpg")> /dev/null -gt 530 -o $(identify -format "%w" "series/$TITLE.jpg")> /dev/null -lt 470 -o $(identify -format "%h" "series/$TITLE.jpg")> /dev/null -gt 780 -o $(identify -format "%h" "series/$TITLE.jpg")> /dev/null -lt 700 ]; then
         if ! grep -q "$OUTPUT" whitelist; then
-            echo "$OUTPUT -- image dimension error" >> stoday.txt; return 1
+            echo "$OUTPUT -- image dimension error" >> stoday.txt; sig_abort 1
         fi
     fi
     FINALIZE
@@ -191,10 +201,12 @@ set -xe
             echo "$OUTPUT -- updated" >> stoday.txt
     else
         echo "$OUTPUT -- published" >> stoday.txt
-        #if [ "$2" != --test ]; then sed -i "1s/^/$(sed 's/&/\\&/g' <<< "$TITLE")\\n/" $LIST; fi
+        #if [ "$2" != --test ]; then
+        sed -i "1s/^/$(sed 's/&/\\&/g' <<< "$TITLE") %$(date +%Y%m%d)\\n/" series_list
     fi
     echo "$TITLE %$OUTPUT".txt >> $JUNK/titles.txt
 }
+trap sig_abort SIGINT
 start=`date +%s`
 ARGS='--connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -ks'; SERVER="root"; LOCAL="persie"
 DIR=~/.turbodl; PXLS=(480 720 1080 2160);
@@ -216,7 +228,7 @@ case "$1" in
     *)  exit;;
 esac
 (while IFS= read -r "U"; do
-    curl $ARGS "$U" | grep -oE "https.*html.*(|title).*</a>" | sed 's:</a>:\n:g; /Releases/d; /Movies/d; /jpg/d; /Series/d; /List/d; /Read More/d; /GAME OF THRONES/d; /gfn/d; /COVID-19/d' > "$JUNK/main" || exit
+    curl $ARGS "$U" | grep -oE "https.*html.*(|title).*</a>" | sed 's:</a>:\n:g; /Releases/d; /Movies/d; /jpg/d; /Series/d; /List/d; /Read More/d; /GAME OF THRONES/d; /gfn/d; /COVID-19/d; / [0-9][0-9][0-9][0-9] /d' > "$JUNK/main" || exit
     sed '/search/d; /^$/d' $JUNK/main | grep -n . > $JUNK/mains; mv $JUNK/mains $JUNK/main
     if [ -e $JUNK/pattern ]; then
         output=$(grep -w -f $JUNK/pattern $JUNK/main | sed "s:.*>::; s: - SEASON.*::")
@@ -226,13 +238,16 @@ esac
     (while IFS= read -r "OUTPUT"; do
         FUNC &
         echo "$!" >> "$JUNK/pid"
+        echo $! >> $JUNK/pids
     done <<< $output; exit) &
     echo "$!" >> "$JUNK/pid"
+    echo $! >> $JUNK/pids
 done < $JUNK/url; exit) &
 echo "$!" >> "$JUNK/pid"
+echo $! >> $JUNK/pids
 while grep -owq -f "$JUNK/pid" <<< $(ls /proc); do printf %b ":: working...\\r"; sleep 5; done
 if [ ! -e stoday.txt ]; then
-    echo 'null posts'; exit
+    exit
 else
     if [ "$USER" == $SERVER ]; then
         if [ -e $JUNK/titles.txt ]; then
