major fixes

diff --git a/advance b/advance
--- a/advance
+++ b/advance
@@ -34,14 +34,21 @@ PARSE(){
         #elif [ $D -gt 99 ]; then
         #    TAGGG="1$D"
         fi
-        if ! grep -qiE "($TAG|$TAGG|$TAGGG)" $JUNK/"$OUTPUT.links"; then
-            if [ ! -e $JUNK/"$OUTPUT.link" ]; then
-                if [ $D == 10 ]; then unset CHECK; rm $JUNK/"$OUTPUT.links"; return; else D=$((D+1)); continue; fi
-            else
-                break
-            fi
-        fi
+        #if ! grep -qiE "($TAG|$TAGG|$TAGGG)" $JUNK/"$OUTPUT.links"; then
+            #if [ ! -e $JUNK/"$OUTPUT.link" ]; then
+                #if [ $D == 10 ]; then unset CHECK; rm $JUNK/"$OUTPUT.links"; return; else D=$((D+1)); #continue; fi
+        #    else
+        #        break
+        #    fi
+        #fi
         if grep -qi 'korean' <<< "$OUTPUT"; then
+            if ! grep -qi "$TAGG" $JUNK/"$OUTPUT.links"; then
+                if [ ! -e $JUNK/"$OUTPUT.link" ]; then
+                    if [ $D == 10 ]; then unset CHECK; rm $JUNK/"$OUTPUT.links"; return; else D=$((D+1)); continue; fi
+                else
+                    break
+                fi
+            fi
             echo -e "" >> $JUNK/"$OUTPUT.link"
             for PXL in "${PXLS[@]}"; do
                 grep -i "$TAGG" $JUNK/"$OUTPUT.links" | grep -vE '(360|480|540|720|1080|2160)p' >> $JUNK/"$OUTPUT.link" || true
@@ -52,13 +59,27 @@ PARSE(){
             done
         elif grep -qi 'anime' <<< "$OUTPUT"; then
             break #find better parsing code for anime
+            if ! grep -qi "$TAGGG" $JUNK/"$OUTPUT.links"; then
+                if [ ! -e $JUNK/"$OUTPUT.link" ]; then
+                    if [ $D == 10 ]; then unset CHECK; rm $JUNK/"$OUTPUT.links"; return; else D=$((D+1)); continue; fi
+                else
+                    break
+                fi
+            fi
             #echo -e "" >> $JUNK/"$OUTPUT.link"
             #for PXL in "${PXLS[@]}"; do
-                #grep -i "$TAGGG" $JUNK/"$OUTPUT.links" | grep -vE '(360|480|540|720|1080|2160)p' >> $JUNK/"$OUTPUT.link" || true
-                #grep -ivE "$TAGGG.*($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -qiE "$TAGGG.*($PXL|${PXL}p)" && echo -e "$(grep -ivE "$TAGGG.*($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -iE "$TAGGG.*($PXL|${PXL}p)")" >> $JUNK/"$OUTPUT.link" || true
+            #    grep -i "$TAGGG" $JUNK/"$OUTPUT.links" | grep -vE '(360|480|540|720|1080|2160)p' >> $JUNK/"$OUTPUT.link" || true
+            #    grep -ivE "$TAGGG.*($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -qiE "$TAGGG.*($PXL|${PXL}p)" && echo -e "\\n${PXL}p\\n$(grep -ivE "$TAGGG.*($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -iE "$TAGGG.*($PXL|${PXL}p)")" >> $JUNK/"$OUTPUT.link" || true
             #    continue
             #done
         else
+            if ! grep -qi "$TAG" $JUNK/"$OUTPUT.links"; then
+                if [ ! -e $JUNK/"$OUTPUT.link" ]; then
+                    if [ $D == 10 ]; then unset CHECK; rm $JUNK/"$OUTPUT.links"; return; else D=$((D+1)); continue; fi
+                else
+                    break
+                fi
+            fi
             if ! grep -qi "Season $D" $JUNK/"$OUTPUT.link" 2> /dev/null; then echo -e "\\n<h5>Season $D</h5>" >> $JUNK/"$OUTPUT.link"; fi
             for PXL in "${PXLS[@]}"; do
                 grep -i "$TAG" $JUNK/"$OUTPUT.links" | grep -vE '(360|480|540|720|1080|2160)p' >> $JUNK/"$OUTPUT.link" || true
@@ -85,7 +106,7 @@ CROSS_CHECK(){  ###fix
             if grep -q 'http' $JUNK/"$OUTPUT.wp_links"; then
                 grep -o '<a.*http.*a>' $JUNK/"$OUTPUT.links" | sort -n > $JUNK/"$OUTPUT.dl" && sort -n $JUNK/"$OUTPUT.wp_links" > $JUNK/"$OUTPUT.wp"
                 if cmp $JUNK/"$OUTPUT.wp" $JUNK/"$OUTPUT.dl"; then
-                    echo 'no need to update'; sig_abort 1
+                    echo "$OUTPUT -- no need to update" >> stoday.txt; sig_abort 1
                 else
                     if [ "$USER" == "$SERVER" ]; then
                         if ! grep -q -- "--test" <<< "$@"; then DELETE_WP_POST; fi; echo "deleted $OUTPUT"
@@ -157,10 +178,10 @@ FUNC(){
     IMDB_ID=$(curl $ARGS --header "Content-Type: application/json" --header "trakt-api-version: 2" --header "trakt-api-key: 64ba02e985f18ec3a00186209b3605cfbbeedf9890898e3a06b8e020111e8194" "https://api.trakt.tv/search/tmdb/$TMDB_ID?type=show" | jq -r ".[0].show.ids.imdb")
     ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT -- false trakt API response" >> stoday.txt && sig_abort 1
     (exec 3>&1 4>&2; trap 'exec 2>&4 1>&3' 0 1 2 3; exec 1>"logs/${OUTPUT}_eztv.log" 2>&1
-    declare -a PID; I=1; J=100; A=0
+    declare -a PID; I=1; J=100; A=0; touch $JUNK/"$OUTPUT.mg"
     while true; do
-        EZTV_API=$(curl $ARGS --header "Content-Type: application/json" "https://eztv.io/api/get-torrents?imdb_id=$(sed 's:tt::' <<< $IMDB_ID)&limit=100&page=$I" || true)
-        if [ "$EZTV_API" == '' ]; then break; fi
+        EZTV_API=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -ks --header "Content-Type: application/json" "https://eztv.io/api/get-torrents?imdb_id=$(sed 's:tt::' <<< $IMDB_ID)&limit=100&page=$I" || true)
+        if [ "$EZTV_API" == '' ]; then rm $JUNK/"$OUTPUT.mg"; break; fi
         if [ $(jq '.torrents_count' <<< "$EZTV_API") == 0 ]; then rm $JUNK/"$OUTPUT.site"; exit; fi
         (set +xe
         while [ $A -lt $(jq -r '.torrents | length' <<< "$EZTV_API") ]; do
@@ -315,8 +336,9 @@ echo -e ":: working...done!"
 end=`date +%s`
 runtime=$(echo -e "$end - $start" | bc -l)
 echo -e ":: $runtime seconds"
+if [ "$USER" == $SERVER ]; then bash /root/turbodl/mail; fi
 #for series
-#curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s --header "Content-Type: application/json" 'https://eztv.io/api/get-torrents?imdb_id=6048596' | jq .
+#curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -ks --header "Content-Type: application/json" 'https://eztv.io/api/get-torrents?imdb_id=6048596' | jq .
 #for movies
 #curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s --header "Content-Type: application/json" 'https://yts.mx/api/v2/list_movies.json?query_term=tt1502397' | jq .
 #magnet:?xt=urn:btih:
