Update mail

diff --git a/mail b/mail
--- a/mail
+++ b/mail
@@ -1,15 +1,24 @@
 #!/bin/env bash
+set -ex
 DIR=~/.turbodl
 if [ -d "$DIR" ]; then
     cd "$DIR"
 fi
 
 if [ -z "$(ls -A errors)" ]; then
-    echo | mutt -s 'turbodlbot | movies' -i mtoday.txt -- persie@turbodl.xyz info@turbodl.xyz
-    echo | mutt -s 'turbodlbot | series' -i stoday.txt -- persie@turbodl.xyz info@turbodl.xyz
+    if [ -e mtoday.txt ]; then
+        echo | mutt -s 'turbodlbot | movies' -i mtoday.txt -a errors/* -- persie@turbodl.xyz info@turbodl.xyz
+    fi
+    if [ -e stoday.txt ]; then
+        echo | mutt -s 'turbodlbot | series' -i stoday.txt -- persie@turbodl.xyz info@turbodl.xyz
+    fi
 else
-    echo | mutt -s 'turbodlbot | movies' -i mtoday.txt -a errors/* -- persie@turbodl.xyz info@turbodl.xyz
-    echo | mutt -s 'turbodlbot | series' -i stoday.txt -a errors/* -- persie@turbodl.xyz info@turbodl.xyz
+    if [ -e mtoday.txt ]; then
+        echo | mutt -s 'turbodlbot | movies' -i mtoday.txt -- persie@turbodl.xyz info@turbodl.xyz
+    fi
+    if [ -e stoday.txt ]; then
+        echo | mutt -s 'turbodlbot | series' -i stoday.txt -- persie@turbodl.xyz info@turbodl.xyz
+    fi
 fi
 echo | mutt -s 'turbodlbot | movies logs' -i mlogs.txt -a movie_list.txt -- persie@turbodl.xyz
 echo | mutt -s 'turbodlbot | series logs' -i slogs.txt -a series_list.txt -- persie@turbodl.xyz
