updated

diff --git a/movies b/movies
--- a/movies
+++ b/movies
@@ -1,7 +1,7 @@
 #!/bin/env bash
 DIR=~/.turbodl
 if [ -d "$DIR" ]; then
-    cd "$DIR"; rm complete/* errors/* today.txt titles.txt 2> /dev/null
+    cd "$DIR"; rm complete/* errors/* mtoday.txt titles.txt 2> /dev/null
 else
     mkdir -p "$DIR"/complete "$DIR"/errors; cd "$DIR"
 fi
@@ -28,7 +28,7 @@ output2=$(grep ^'<a href=.*html.*title=.*</a>' <<< "$URL" | sed "s/'>.*//")
 if [ "$USER" != persie ]; then
     exec 3>&1 4>&2
     trap 'exec 2>&4 1>&3' 0 1 2 3
-    exec 1>logs.txt 2>&1
+    exec 1>mlogs.txt 2>&1
 fi
 set -ex
 
@@ -41,34 +41,34 @@ while IFS= read -r "OUTPUT"; do
     grep -qiE "(hd.*cm|HDCAM|HDTS).*mkv" <<< "$LINKS" && continue
 
     NAME=$(sed -e 's/  $//; s/ $//; s/\./ /g; s/_/ /g; s/[ -.][0-9][0-9][0-9][0-9].*//; s/ ([0-9][0-9][0-9][0-9]).*//' <<< "$OUTPUT")
-    YEAR=$(grep -oE '([0-9][0-9][0-9][0-9]$|[0-9][0-9][0-9][0-9])' <<< "$OUTPUT" || echo 'null')
-    grep -q 'null' <<< "$YEAR" && echo "$OUTPUT   -->   year not found" >> today.txt && continue
+    YEAR=$(grep -woE '([0-9][0-9][0-9][0-9]$|[0-9][0-9][0-9][0-9])' <<< "$OUTPUT" || echo 'null')
+    grep -q 'null' <<< "$YEAR" && echo "$OUTPUT   -->   year not found" >> mtoday.txt && continue
 
     TMDB_API=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/search/movie?api_key=0dec8436bb1b7de2bbcb1920ac31111f&query=$(sed "s/ /%20/g" <<< "$NAME")&page=1&year=$YEAR" || exit)
-    if [ $(jq '.total_results' <<< "$TMDB_API") == 0 ]; then echo "$OUTPUT   -->   not found" >> today.txt; continue; fi
+    if [ $(jq '.total_results' <<< "$TMDB_API") == 0 ]; then echo "$OUTPUT   -->   not found" >> mtoday.txt; continue; fi
     A=0
     while [ "$A" -lt $(jq '.total_results' <<< "$TMDB_API") ]; do
         if grep -q "$YEAR" <<< $(jq -r ".results[$A].release_date" <<< "$TMDB_API"); then
             POSTER="https://image.tmdb.org/t/p/w500$(jq -r ".results[$A] | .poster_path" <<< "$TMDB_API")"
-            #if grep -q 'null' <<< "$POSTER"; then echo "$OUTPUT   -->   no poster" >> today.txt && continue 2; fi
+            #if grep -q 'null' <<< "$POSTER"; then echo "$OUTPUT   -->   no poster" >> mtoday.txt && continue 2; fi
             TMDB_ID=$(jq -r ".results[$A] | .id" <<< ""$TMDB_API"")
             OVERVIEW=$(jq -r ".results[$A] | .overview" <<< "$TMDB_API")
             break
         elif grep -q "$((YEAR+1))" <<< $(jq -r ".results[$A].release_date" <<< "$TMDB_API"); then
             POSTER="https://image.tmdb.org/t/p/w500$(jq -r ".results[$A] | .poster_path" <<< "$TMDB_API")"
-            #if grep -q 'null' <<< "$POSTER"; then echo "$OUTPUT   -->   no poster" >> today.txt && continue 2; fi
+            #if grep -q 'null' <<< "$POSTER"; then echo "$OUTPUT   -->   no poster" >> mtoday.txt && continue 2; fi
             TMDB_ID=$(jq -r ".results[$A] | .id" <<< ""$TMDB_API"")
             OVERVIEW=$(jq -r ".results[$A] | .overview" <<< "$TMDB_API")
             break
         else
             if [ $(jq '.total_results' <<< "$TMDB_API") == 1 ]; then
                 POSTER="https://image.tmdb.org/t/p/w500$(jq -r ".results[$A] | .poster_path" <<< "$TMDB_API")"
-                #if grep -q 'null' <<< "$POSTER"; then echo "$OUTPUT   -->   no poster" >> today.txt && continue 2; fi
+                #if grep -q 'null' <<< "$POSTER"; then echo "$OUTPUT   -->   no poster" >> mtoday.txt && continue 2; fi
                 TMDB_ID=$(jq -r ".results[$A] | .id" <<< "$TMDB_API")
                 OVERVIEW=$(jq -r ".results[$A] | .overview" <<< "$TMDB_API")
                 break
             elif [ "$A" == $(jq '.total_results' <<< "$TMDB_API") ]; then
-                echo "$OUTPUT   -->   not found" >> today.txt
+                echo "$OUTPUT   -->   not found" >> mtoday.txt
                 continue 2
             fi
             A=$((A+1))
@@ -94,10 +94,10 @@ while IFS= read -r "OUTPUT"; do
     A=0
 
     IMDB_ID=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s --header "Content-Type: application/json" --header "trakt-api-version: 2" --header "trakt-api-key: 64ba02e985f18ec3a00186209b3605cfbbeedf9890898e3a06b8e020111e8194" "https://api.trakt.tv/search/tmdb/$TMDB_ID?type=movie" | jq -r '.[0].movie.ids.imdb' || exit)
-    ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT   --> IMDB error getting data" >> today.txt && continue
+    ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT   --> IMDB error getting data" >> mtoday.txt && continue
 
     OMDB_API=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?i=$IMDB_ID&plot=short&apikey=7759dbc7" || exit)
-    grep "Error getting data" <<< "$OMDB_API" && echo "$OUTPUT   --> OMDB error getting data" >> today.txt && continue
+    grep "Error getting data" <<< "$OMDB_API" && echo "$OUTPUT   --> OMDB error getting data" >> mtoday.txt && continue
     TITLE="$(jq -r ".Title" <<< "$OMDB_API") ($YEAR)"
     PLOT=$(jq -r '.Plot' <<< "$OMDB_API"); grep -q 'N/A' <<< "$PLOT" && PLOT="$OVERVIEW";CAST=$(jq -r '.Actors' <<< "$OMDB_API")
     GENRE=$(jq -r '.Genre' <<< "$OMDB_API")
@@ -112,10 +112,10 @@ while IFS= read -r "OUTPUT"; do
             fi
             curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s "$POSTER" -o errors/"$TITLE".jpg
             if [ $(identify -format "%w" errors/"$TITLE".jpg)> /dev/null -gt 530 -o $(identify -format "%w" errors/"$TITLE".jpg)> /dev/null -lt 470 -o $(identify -format "%h" errors/"$TITLE".jpg)> /dev/null -gt 780 -o $(identify -format "%h" errors/"$TITLE".jpg)> /dev/null -lt 720 ]; then
-            rm errors/"$TITLE".jpg; echo "$OUTPUT   -->   invalid image height/weight dimension & rating/genre" >> 'today.txt'
+            rm errors/"$TITLE".jpg; echo "$OUTPUT   -->   invalid image height/weight dimension & rating/genre" >> 'mtoday.txt'
             continue
             fi
-            echo "$OUTPUT   -->   rating/genre not available" >> 'today.txt'
+            echo "$OUTPUT   -->   rating/genre not available" >> 'mtoday.txt'
             continue
         else
             #grep -q 'N/A' <<< "$RATING" && RATING=$(grep "$OUTPUT" whitelist | grep -oE '([0-9]\.[0-9]|[0-9][0-9]\.[0-9]|N/A)')
@@ -167,7 +167,7 @@ set -x
                 break
             else
                 A=$((A+1))
-                if [ $A == $(jq length <<< "$WP_RESULTS") ]; then echo "$OUTPUT   -->   conflicting error" >> today.txt && continue 2; fi
+                if [ $A == $(jq length <<< "$WP_RESULTS") ]; then echo "$OUTPUT   -->   conflicting error" >> mtoday.txt && continue 2; fi
             fi
         done
     fi
@@ -179,11 +179,11 @@ set -x
         else
             echo -e "<p style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\nDownload Links:\\n$LINKS\\n</p>\\n\\nTags: $GENRE, $YEAR" > errors/"$OUTPUT"
         fi
-        echo "$OUTPUT   -->   invalid image height/weight dimension" >> 'today.txt'
+        echo "$OUTPUT   -->   invalid image height/weight dimension" >> 'mtoday.txt'
         continue
     fi
 
-    if grep -qowiF "$TITLE" movie_list.txt; then echo "$TITLE  -->   updated" >> today.txt; else echo "$TITLE" >> today.txt && sed -i "1s/^/$TITLE\\n/" movie_list.txt; fi
+    if grep -qowiF "$TITLE" movie_list.txt; then echo "$TITLE  -->   updated" >> mtoday.txt; else echo "$TITLE" >> mtoday.txt && sed -i "1s/^/$TITLE\\n/" movie_list.txt; fi
     echo "$TITLE #$OUTPUT" >> titles.txt
     if [ "$KEY" ]; then
         echo -e "<p style=\"text-align: center;\">\\n$PLOT\\n\\n<center>Trailer:<iframe src=\"https://www.youtube-nocookie.com/embed/$KEY?modestbranding=1&showinfo=0&rel=0&iv_load_policy=3&color=white&controls=0\" width=\"500\" height=\"300\" frameborder=\"0\"></iframe></centre>\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\nDownload Links:\\n$LINKS\\n</p>\\n\\nTags: $GENRE, $YEAR" > complete/"$OUTPUT"
@@ -192,18 +192,19 @@ set -x
     fi
 done <<< "$output"
 
-if [ ! -e today.txt ]; then
-    if [ "$USER" != persie ]; then
-        echo | mutt -s 'turbodlbot | movies logs' -i logs.txt movie_list.txt -- persie@turbodl.xyz
+if [ ! -e mtoday.txt ]; then
+    echo 'no movies posted'
+    #if [ "$USER" != persie ]; then
+        #echo | mutt -s 'turbodlbot | movies logs' -i logs.txt movie_list.txt -- persie@turbodl.xyz
         #curl --header 'Access-Token: o.6xtXrrxcyGxw6LOKD6fTnIdHXXQXh9jT' \
         #--header 'Content-Type: application/json' \
         #--data-binary {"body":"$(cat logs.txt)","title":"turbodlbot | movies logs","type":"note"} \
         #--request POST \
         #https://api.pushbullet.com/v2/pushes
-    fi
+    #fi
     exit
 fi
-sed -i "1s/^/$(date)\\n--------------------------------\\n/" today.txt
+sed -i "1s/^/$(date)\\n--------------------------------\\n/" mtoday.txt
 
 if [ "$USER" != persie ]; then
     if [ -e titles.txt ]; then
@@ -214,12 +215,12 @@ if [ "$USER" != persie ]; then
         done <<< "$SORTED_POSTS"
     fi
 
-    if [ -z "$(ls -A errors)" ]; then
-        echo | mutt -s 'turbodlbot | movies' -i today.txt -- persie@turbodl.xyz info@turbodl.xyz
-    else
-        echo | mutt -s 'turbodlbot | movies' -i today.txt -a errors/* -- persie@turbodl.xyz info@turbodl.xyz
-    fi
-    echo | mutt -s 'turbodlbot | movies logs' -i logs.txt movie_list.txt -- persie@turbodl.xyz
+    #if [ -z "$(ls -A errors)" ]; then
+    #    echo | mutt -s 'turbodlbot | movies' -i mtoday.txt -- persie@turbodl.xyz info@turbodl.xyz
+    #else
+    #    echo | mutt -s 'turbodlbot | movies' -i mtoday.txt -a errors/* -- persie@turbodl.xyz info@turbodl.xyz
+    #fi
+    #echo | mutt -s 'turbodlbot | movies logs' -i logs.txt movie_list.txt -- persie@turbodl.xyz
     #curl --header 'Access-Token: o.6xtXrrxcyGxw6LOKD6fTnIdHXXQXh9jT' \
     #--header 'Content-Type: application/json' \
     #--data-binary "{'body':$(cat logs.txt),'title':'turbodlbot | movies logs','type':'note'}" \
