WIP

diff --git a/new b/new
--- a/new
+++ b/new
@@ -1,12 +1,38 @@
 #!/bin/env bash
 set -e
 sig_abort(){
-    if [ $1 ]; then
+    if [ "$1" == 1 ]; then
         xargs kill <$JUNK/"$OUTPUT.pids" 2> /dev/null
     else
         xargs kill <$JUNK/pids 2> /dev/null
     fi
     return 1
+}
+PARSE(){
+    (exec 3>&1 4>&2; trap 'exec 2>&4 1>&3' 0 1 2 3; exec 1>"logs/${OUTPUT}_parse.log" 2>&1
+    if [ "$USER" != "$LOCAL" ]; then
+        while IFS= read -r "LINE"; do
+            if ! grep -q 'http' <<< $LINE; then continue; fi
+            SIZE=$(wget -o - -t 5 --timeout=5 --tries=3 --spider "$(grep -oE "http.*(mkv|mp4|avi)" <<< $LINE | sed -e 's/.>.*//')" | grep Length | sed 's/.*(//; s/).*//' || true)
+            grep -qE "(G|M)" <<< $SIZE && echo "$LINE - $SIZE"B >> $JUNK/"$OUTPUT.link" || echo "$LINE - N/A" >> $JUNK/"$OUTPUT.link"
+        done < $JUNK/"$OUTPUT.links"
+        mv $JUNK/"$OUTPUT.link" $JUNK/"$OUTPUT.links"
+    fi
+    grep . links | grep -vE '(480|720|1080|2160)p' >> link || true
+    for PXL in "${PXLS[@]}"; do
+        grep -ivE "($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.links" | grep -iE "($PXL|${PXL}p)" && echo -e "\\n${PXL}p\\n$(grep -iE "($PXL|${PXL}p)" $JUNK/"$OUTPUT.links" | grep -vE '(x264|x265)')" >> $JUNK/"$OUTPUT.link"
+        grep -ivE "($PXL|${PXL}p).*(x264|x265)" $JUNK/"$OUTPUT.magnets" | grep -iE "($PXL|${PXL}p)" && echo -e "\\n${PXL}p\\n$(grep -iE "($PXL|${PXL}p)" $JUNK/"$OUTPUT.magnets" | grep -vE '(x264|x265)')" >> $JUNK/"$OUTPUT.mg" || true
+        grep -qiE "($PXL|${PXL}p).*x264" $JUNK/"$OUTPUT.links" && echo -e "\\n${PXL}p x264\\n$(grep -iE "($PXL|${PXL}p).*x264" $JUNK/"$OUTPUT.links")" >> $JUNK/"$OUTPUT.link"
+        grep -qiE "($PXL|${PXL}p).*x264" $JUNK/"$OUTPUT.magnets" && echo -e "\\n${PXL}p x264\\n$(grep -iE "($PXL|${PXL}p).*x264" $JUNK/"$OUTPUT.magnets")" >> $JUNK/"$OUTPUT.mg" || true
+        grep -qiE "($PXL|${PXL}p).*x265" $JUNK/"$OUTPUT.links" && echo -e "\\n${PXL}p x265\\n$(grep -iE "($PXL|${PXL}p).*x265" $JUNK/"$OUTPUT.links")" >> $JUNK/"$OUTPUT.link"
+        grep -qiE "($PXL|${PXL}p).*x265" $JUNK/"$OUTPUT.magnets" && echo -e "\\n${PXL}p x265\\n$(grep -iE "($PXL|${PXL}p).*x265" $JUNK/"$OUTPUT.magnets")" >> $JUNK/"$OUTPUT.mg" || true
+    done
+    if [ -e $JUNK/"$OUTPUT.link" ]; then mv $JUNK/"$OUTPUT.link" $JUNK/"$OUTPUT.links"; fi;
+    sed -i 's/ target=\"_blank\"//g; s/ rel=\"nofollow\"//' $JUNK/"$OUTPUT.links"
+    if [ -e $JUNK/"$OUTPUT.mg" ]; then mv $JUNK/"$OUTPUT.mg" $JUNK/"$OUTPUT.magnets"; fi;
+    sed -i "1s:^:\n<h3>Magnets\:</h3>\n:" $JUNK/"$OUTPUT.magnets"; rm $JUNK/"$OUTPUT.site"
+    rm $JUNK/"$OUTPUT.site") &
+    echo "$!" >> $JUNK/pids
 }
 FUNC(){
     BLACKLIST=$(jq '.[0].blacklist' list); WHITELIST=$(jq '.[0].whitelist' list)
@@ -15,7 +41,89 @@ FUNC(){
     set -xe; echo -e "\\n${OUTPUT}${TASKS}\\n-----------------------"
     if grep -q "$OUTPUT" <<< $BLACKLIST; then echo "$OUTPUT -- blacklisted"; return 1; fi #blaclist if title is in blacklist file
     curl $ARGS $(grep "$OUTPUT" "$JUNK/main" | grep -o http.*html) > "$JUNK/$OUTPUT.site" || exit #download series page
-    grep -oiE "(<span style=\"font-family.*http|<a.*href=).*(|S[0-9][0-9]E[0-9][0-9]).*(mkv|mp4|avi).*</a>" site | sed "s/.*<a/<a/; s/a>.*/a>/; s/CLICK HERE FOR SUBTITLES /Subtitles/; /Load more/d; /img/d; /lightdl/d;s/<br \/>//; s/<a.*href/<a href/" > "$JUNK/$OUTPUT.links"
+    grep -oiE "(<span style=\"font-family.*http|<a.*href=).*(|S[0-9][0-9]E[0-9][0-9]).*(mkv|mp4|avi).*</a>" "$JUNK/$OUTPUT.site" | sed "s:(twitchdl.com)::;s:</a>:(turbodl.xyz)</a>:g; s/.*<a/<a/; s/a>.*/a>/; s/CLICK HERE FOR SUBTITLES /Subtitles/; /Load more/d; /img/d; /lightdl/d;s/<br \/>//; s/<a.*href/<a href/" > "$JUNK/$OUTPUT.links"   #grab links and strip off junk
+    sed -i '/subtitle/d; s:<.*span.*span>::g; /^<span/d; /Load more/d; /blogger.com/d' "$JUNK/$OUTPUT.links" #get links and remove junk from links & add 'turbodl.xyz' to the end of links without it
+    grep -q 'http' $JUNK/"$OUTPUT.links" && LINKS_AVAILABLE=YES #check for links in file and tag it
+    NAME=$(sed -e 's/  $//; s/ $//; s/\./ /g; s/_/ /g; s/[ -.][0-9][0-9][0-9][0-9].*//; s/ ([0-9][0-9][0-9][0-9]).*//; s/ - Collection//; s/ Collection//; s/ (Tv-Series)//; s/ (Anime)//' <<< "$OUTPUT")   #get title of movie from page
+    grep -q "$OUTPUT=" <<< $WHITELIST && NAME=$(sed "/$OUTPUT/!d; s/.*$OUTPUT=//; s/\".*//")    #replace title of movie if title is a misnomer
+    TMDB_API=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/search/movie?api_key=0dec8436bb1b7de2bbcb1920ac31111f&query=$(sed "s/ /%20/g" <<< "$NAME")&page=1&" || exit)   #themoviedb AP
+    if [ $(jq '.total_results' <<< "$TMDB_API") == 0 ]; then echo "$OUTPUT -- not found" >> results.txt; return 1; fi    #execute if movie is not found in themoviedb
+    A=0
+    while true; do  #loop themoviedb results for specific movie using release dates
+        if [ "$(jq -r ".results[$A] | .release_date" <<< "$TMDB_API" | sed 's:-::g')" == null ]; then
+            echo "$OUTPUT -- null" >> results.txt; sig_abort 1
+        fi
+        if [ "$(jq -r ".results[$A] | .release_date" <<< "$TMDB_API" | sed 's:-::g')" -lt 19991201 ]; then
+            A=$((A+1)); continue    #discard movie if year is less than 1999
+        else
+            if [ $(jq -r ".results[$A] | .poster_path" <<< "$TMDB_API") != 'null' ]; then
+                TMDB_ID=$(jq -r ".results[$A] | .id" <<< ""$TMDB_API"")     #movie ID
+                POSTER="https://image.tmdb.org/t/p/w500$(jq -r ".results[$A] | .poster_path" <<< "$TMDB_API")"  #get movie poster
+                break
+            else
+                echo "$OUTPUT -- no poster" >> results.txt && return 1  #discard post if no poster is found
+            fi
+        fi
+    done    #loop end
+    (GET_TRAILER(){     #funtion to get trailer key
+        while [ $A != $(jq '.results | length' <<< "$TRAILERS") ]; do
+            if [ $1 == "$(jq -r ".results[$A].type" <<< "$TRAILERS")" ]; then
+                echo "$OUTPUT=$(jq -r ".results[$A].key" <<< "$TRAILERS")" >> $JUNK/keys; break
+            elif [ $A == $(jq '.results | length' <<< "$TRAILERS") ]; then
+                break
+            else
+                A=$((A+1)); continue
+            fi
+        done
+    }
+    set +xe
+    #get trailers
+    TRAILERS=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/movie/$TMDB_ID/videos?api_key=0dec8436bb1b7de2bbcb1920ac31111f" || exit)
+    if [ "$(jq '.results | length' <<< $TRAILERS)" != '0' ]; then
+        _TYPES=(Trailer Teaser Featurette)
+        for _TYPE in "${_TYPES[@]}"; do A=0; GET_TRAILER $_TYPE; if [ $KEY ]; then break; fi; done
+    fi; exit) &
+    #end
+    set -xe
+    IMDB_ID=$(curl $ARGS --header "Content-Type: application/json" --header "trakt-api-version: 2" --header "trakt-api-key: 64ba02e985f18ec3a00186209b3605cfbbeedf9890898e3a06b8e020111e8194" "https://api.trakt.tv/search/tmdb/$TMDB_ID?type=movie" | jq -r ".[0].movie.ids.imdb")     #traktAPI
+    ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT -- false trakt API response" >> results.txt && sig_abort 1
+    #background code to get magnets
+    (exec 3>&1 4>&2; trap 'exec 2>&4 1>&3' 0 1 2 3; exec 1>"logs/${OUTPUT}_yts.log" 2>&1
+    declare -a PID; I=1; J=100; A=0; touch $JUNK/"$OUTPUT.mg"
+    while true; do
+        YTS_API=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s --header "Content-Type: application/json" "https://yts.mx/api/v2/list_movies.json?query_term=$IMDB_ID" || true)
+        if [ "$YTS_API" == '' ]; then rm $JUNK/"$OUTPUT.mg"; break; fi
+        if [ $(jq '.data.movie_count' <<< "$YTS_API") == 0 ]; then rm $JUNK/"$OUTPUT.site" $JUNK/"$OUTPUT.mg"; exit; fi
+        ( #set +xe
+        while [ $A -le $(jq -r '.data.movie_count | length' <<< "$YTS_API") ]; do
+            echo "<a href=\"magnet:?xt=urn:btih:$(jq -r ".data.movies | .[].torrents | .[$A].hash" <<< "$YTS_API")\">$(jq -r ".data.movies | .[].title_long" <<< "$YTS_API") [$(jq -r ".data.movies | .[].torrents | .[$A].quality" <<< "$YTS_API")] [torrent] (turbodl.xyz)</a> - $(jq -r ".data.movies | .[].torrents | .[$A].size" <<< "$YTS_API")" >> "$JUNK/$OUTPUT.mg"
+            A=$((A+1))
+        done; exit) &
+        set +x; PID+=($!); echo $! | tee -a $JUNK/pids $JUNK/"$OUTPUT.pids"; set -x
+        if [ $(jq '.data.movie_count' <<< "$YTS_API") -gt $J ]; then
+            I=$((I+1)); J=$((J+100)); A=0; continue
+        fi
+        break
+    done
+    if [ ! -e $JUNK/"$OUTPUT.mg" ]; then rm $JUNK/"$OUTPUT.site"; return 1; fi
+    PID=$(echo ${PID[@]}|tr " " "|")
+    while grep -Eowq "$PID" <<< $(ls /proc); do sleep 7; continue; done
+    while IFS= read -r "MAG"; do
+        grep -F "$MAG" $JUNK/"$OUTPUT.mg" >> $JUNK/"$OUTPUT.magnets"
+    done <<< $(grep -o ">.*" "$JUNK/$OUTPUT.mg" | sort -n)
+    rm $JUNK/"$OUTPUT.mg"; exit) &
+    #end
+    set +x; echo $! | tee -a $JUNK/pids $JUNK/"$OUTPUT.pids"; set -x
+    OMDB_API=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?i=$IMDB_ID&plot=short&apikey=7759dbc7" || exit)
+    grep "Error getting data" <<< "$OMDB_API" && echo "$OUTPUT -- false OMDB API response" >> results.txt && sig_abort 1
+    YEAR=$(jq -r '.Year' <<< $OMDB_API); TITLE="$(jq -r ".Title" <<< "$OMDB_API")$INSERT($YEAR)"
+    CAST=$(jq -r '.Actors' <<< "$OMDB_API"); GENRE=$(jq -r '.Genre' <<< "$OMDB_API"); RATING=$(jq -r '.imdbRating' <<< "$OMDB_API"); PLOT=$(jq -r '.Plot' <<< "$OMDB_API")
+    grep -qiE '(documentary|reality-tv|talk-show|Game-Show)' <<< "$GENRE" && ! grep -q "$OUTPUT" <<< $WHITELIST && sig_abort 1
+    if ! grep -q "$OUTPUT" <<< $WHITELIST; then if [ "$GENRE" == 'N/A' ]; then echo "$OUTPUT -- N/A" >> results.txt && sig_abort 1; fi; fi
+    grep -owF "$TITLE" movie_list && if ! grep -q -- "--test" <<< "$@"; then if [ $(($(date +%Y%m%d)-$(grep -ow "$TITLE.*" movie_list | grep -o '%.*' | sed 's:%::'))) -le 5 ]; then echo "$OUTPUT -- published within 5days" >> results.txt; sig_abort 1; else CROSS_CHECK "$@"; fi; else CROSS_CHECK "$@"; fi
+    echo >> $JUNK/"$OUTPUT.site"; PARSE
+    set +xe; while [ -e $JUNK/"$OUTPUT.site" ]; do sleep 5; continue; done; set -xe
+
 }
 trap sig_abort SIGINT
 start=`date +%s`
@@ -56,12 +164,13 @@ touch $JUNK/file $JUNK/pid $JUNK/pids
     (while IFS= read -r "OUTPUT"; do
         ! grep -q "$OUTPUT" $JUNK/file && echo "$OUTPUT" >> $JUNK/file || continue #skip duplicate URLs
         FUNC "$@" &
-        echo "$!" >> $JUNK/pid
-        echo $! >> $JUNK/pids
+        echo "$!" >> $JUNK/pid; echo $! >> $JUNK/pids
     done <<< $output; exit) &
-    echo "$!" >> $JUNK/pid
-    echo $! >> $JUNK/pids
+    echo "$!" >> $JUNK/pid; echo $! >> $JUNK/pids
 done < $JUNK/url; exit) &
-echo "$!" >> $JUNK/pid
-echo $! >> $JUNK/pids
-while grep -owq -f "$JUNK/pid" <<< $(ls /proc); do printf %b ":: working...\\r"; sleep 5; done
+echo "$!" >> $JUNK/pid; echo $! >> $JUNK/pids
+while grep -owq -f "$JUNK/pids" <<< $(ls /proc); do printf %b ":: working...\\r"; sleep 5; done
+echo -e ":: working...done!"
+end=`date +%s`
+runtime=$(echo -e "$end - $start" | bc -l)
+echo -e ":: $runtime seconds"
