updated

diff --git a/new-advance b/new-advance
--- a/new-advance
+++ b/new-advance
@@ -28,74 +28,69 @@ CROSS_CHECK(){
     exit
 }
 FUNC(){
-
-        exec 3>&1 4>&2; trap 'exec 2>&4 1>&3' 0 1 2 3; exec 1>"logs/$OUTPUT.log" 2>&1
-        unset NAME TMDB_API POSTER TMDB_ID TRAILERS KEY IMDB_ID OMDB_API TITLE CAST GENRE RATING PLOT SAME TYPE
-        set -xe; echo -e "\\n${OUTPUT}${TASKS}\\n-----------------------"
-        if grep -q "$OUTPUT" list; then echo "$OUTPUT -- blacklisted" >> stoday.txt; return; fi #blaclist if title is in blacklist file
-        curl $ARGS $(grep "$OUTPUT" "$JUNK/twitchdl" | grep -o http.*html) > "$JUNK/$OUTPUT.site" || exit #download series page
-        grep -oiE "<a href=.*(S[0-9][0-9]E[0-9][0-9]).*(mkv|mp4|avi).*</a>" "$JUNK/$OUTPUT.site" | sed 's:(twitchdl.com)::;s:</a>:(turbodl.xyz)</a>:g; /imdb/d; s:<br />:\n:g; s:" .*">::g;' > "$JUNK/$OUTPUT.links"
-        sed -i '/subtitle/d; s:<.*span.*span>::g; /^<span/d' "$JUNK/$OUTPUT.links" #get links and remove junk from links & add 'turbodl.xyz' to the end of links without it
-        [ -z "$JUNK/$OUTPUT.links" ] && echo "$OUTPUT -- no links" >> stoday.txt && continue || grep -qE "(hd.*cm|HDCAM|HDCam|CAM|HDTS|HDTC|DVD|dvd|SCR|Scr|scr).*(mkv|mp4|avi)" "$JUNK/$OUTPUT.links" && echo '$OUTPUT is CAM' && continue #remove movies containing CAM like links
-        NAME=$(sed "s: -.*Season.*::" <<< "$OUTPUT")
-        if grep -q "$OUTPUT=" list; then NAME=$(grep "$OUTPUT" list | sed "s/.*$OUTPUT=//; s/;.*//g"); fi
-        TMDB_API=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/search/tv?api_key=0dec8436bb1b7de2bbcb1920ac31111f&query=$(sed "s/ /%20/g" <<< "$NAME")&page=1" || exit)
-        if [ $(jq '.total_results' <<< "$TMDB_API") == 0 ]; then echo "$OUTPUT -- not found" >> stoday.txt; continue; fi
-        A=0
-        while [ "$A" -lt "$(jq '.total_results' <<< $TMDB_API)" ]; do
-            if grep -E "($YEAR|$((YEAR+1))|$((YEAR-1)))" <<< $(jq -r ".results[$A].first_air_date" <<< "$TMDB_API"); then
-                POSTER="https://image.tmdb.org/t/p/w500$(jq -r ".results[$A] | .poster_path" <<< "$TMDB_API")"
-                grep -q null <<< "$POSTER" && echo "$OUTPUT -- null poster" >> stoday.txt && continue 2
-                TMDB_ID=$(jq -r ".results[$A] | .id" <<< ""$TMDB_API"")
-                break
-            fi
-            A=$((A+1))
-        done
-        TRAILER(){
-            GET_TRAILER(){
-                while [ $A != $(jq '.results | length' <<< "$TRAILERS") ]; do
-                    if [ $1 == "$(jq -r ".results[$A].type" <<< "$TRAILERS")" ]; then
-                        KEY=$(jq -r ".results[$A].key" <<< "$TRAILERS"); export KEY; break
-                    elif [ $A == $(jq '.results | length' <<< "$TRAILERS") ]; then
-                        break
-                    else
-                        A=$((A+1)); continue
-                    fi
-                done
-            }
-            set +xe
-            TRAILERS=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/tv/$TMDB_ID/videos?api_key=0dec8436bb1b7de2bbcb1920ac31111f" || exit)
-            if [ "$(jq '.results | length' <<< $TRAILERS)" != '0' ]; then
-                _TYPES=(Trailer Teaser Featurette)
-                for _TYPE in "${_TYPES[@]}"; do A=0; GET_TRAILER $_TYPE; if [ $KEY ]; then break; fi; done
-            fi
-            set -xe
+    BLACKLIST=$(jq '.[0].blacklist' list); WHITELIST=$(jq '.[0].whitelist' list)
+    exec 3>&1 4>&2; trap 'exec 2>&4 1>&3' 0 1 2 3; exec 1>"logs/$OUTPUT.log" 2>&1
+    unset NAME TMDB_API POSTER TMDB_ID TRAILERS KEY IMDB_ID OMDB_API TITLE CAST GENRE RATING PLOT SAME TYPE
+    set -xe; echo -e "\\n${OUTPUT}${TASKS}\\n-----------------------"
+    if grep -q "$OUTPUT" <<< $BLACKLIST; then echo "$OUTPUT -- blacklisted" >> stoday.txt; return; fi #blaclist if title is in blacklist file
+    curl $ARGS $(grep "$OUTPUT" "$JUNK/twitchdl" | grep -o http.*html) > "$JUNK/$OUTPUT.site" || exit #download series page
+    grep -oiE "<a href=.*(S[0-9][0-9]E[0-9][0-9]).*(mkv|mp4|avi).*</a>" "$JUNK/$OUTPUT.site" | sed 's:(twitchdl.com)::;s:</a>:(turbodl.xyz)</a>:g; /imdb/d; s:<br />:\n:g; s:" .*">::g;' > "$JUNK/$OUTPUT.links"
+    sed -i '/subtitle/d; s:<.*span.*span>::g; /^<span/d' "$JUNK/$OUTPUT.links" #get links and remove junk from links & add 'turbodl.xyz' to the end of links without it
+    [ -z "$JUNK/$OUTPUT.links" ] && echo "$OUTPUT -- no links" >> stoday.txt && continue || grep -qE "(hd.*cm|HDCAM|HDCam|CAM|HDTS|HDTC|DVD|dvd|SCR|Scr|scr).*(mkv|mp4|avi)" "$JUNK/$OUTPUT.links" && echo '$OUTPUT is CAM' && continue #remove movies containing CAM like links
+    NAME=$(sed "s: -.*Season.*::" <<< "$OUTPUT")
+    grep -q "$OUTPUT=" $WHITELIST && NAME=$(sed "/$OUTPUT/!d; s/.*$OUTPUT=//; s/\".*//")
+    TMDB_API=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/search/tv?api_key=0dec8436bb1b7de2bbcb1920ac31111f&query=$(sed "s/ /%20/g" <<< "$NAME")&page=1" || exit)
+    if [ $(jq '.total_results' <<< "$TMDB_API") == 0 ]; then echo "$OUTPUT -- not found" >> stoday.txt; continue; fi
+    if [ $(jq -r ".results[0] | .poster_path" <<< "$TMDB_API" != 'null' ]; then
+        TMDB_ID=$(jq -r ".results[0] | .id" <<< ""$TMDB_API"")
+        POSTER="https://image.tmdb.org/t/p/w500$(jq -r ".results[0] | .poster_path" <<< "$TMDB_API")"
+    else
+        echo "$OUTPUT -- no poster" >> stoday.txt && return
+    fi
+    TRAILER(){
+        GET_TRAILER(){
+            while [ $A != $(jq '.results | length' <<< "$TRAILERS") ]; do
+                if [ $1 == "$(jq -r ".results[$A].type" <<< "$TRAILERS")" ]; then
+                    KEY=$(jq -r ".results[$A].key" <<< "$TRAILERS"); export KEY; break
+                elif [ $A == $(jq '.results | length' <<< "$TRAILERS") ]; then
+                    break
+                else
+                    A=$((A+1)); continue
+                fi
+            done
         }
-        TRAILER &
-        IMDB_ID=$(curl $ARGS --header "Content-Type: application/json" --header "trakt-api-version: 2" --header "trakt-api-key: 64ba02e985f18ec3a00186209b3605cfbbeedf9890898e3a06b8e020111e8194" "https://api.trakt.tv/search/tmdb/$TMDB_ID?type=show" | jq -r ".[0].show.ids.imdb")
-        ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT -- false trakt API response" >> stoday.txt && continue
-        OMDB_API=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?i=$IMDB_ID&plot=short&apikey=7759dbc7" || exit)
-        grep "Error getting data" <<< "$OMDB_API" && echo "$OUTPUT -- false OMDB API response" >> stoday.txt && continue
-        YEAR=$(jq -r '.Year' <<< $OMDB_API); TITLE="$(jq -r ".Title" <<< "$OMDB_API") ($YEAR)"
-        CAST=$(jq -r '.Actors' <<< "$OMDB_API"); GENRE=$(jq -r '.Genre' <<< "$OMDB_API")
-        RATING=$(jq -r '.imdbRating' <<< "$OMDB_API")
-        grep -qiE '(documentary|reality-tv|talk-show)' <<< "$GENRE" && ! grep -q "$OUTPUT" list && continue
-        if ! grep -q "$OUTPUT" list; then
-            if [ "$RATING" == 'N/A' -o "$GENRE" == 'N/A' ]; then
-                echo "$OUTPUT -- N/A" >> $1'today.txt' && continue
-            fi
+        set +xe
+        TRAILERS=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/tv/$TMDB_ID/videos?api_key=0dec8436bb1b7de2bbcb1920ac31111f" || exit)
+        if [ "$(jq '.results | length' <<< $TRAILERS)" != '0' ]; then
+            _TYPES=(Trailer Teaser Featurette)
+            for _TYPE in "${_TYPES[@]}"; do A=0; GET_TRAILER $_TYPE; if [ $KEY ]; then break; fi; done
         fi
-        PLOT=$(jq -r '.Plot' <<< "$OMDB_API")
-        #grep -owF "$TITLE" series_list && CROSS_CHECK; break
-        echo "$TITLE" >> today.txt;
-        #sed 's/–/, /'
+        set -xe
+    }
+    TRAILER &
+    IMDB_ID=$(curl $ARGS --header "Content-Type: application/json" --header "trakt-api-version: 2" --header "trakt-api-key: 64ba02e985f18ec3a00186209b3605cfbbeedf9890898e3a06b8e020111e8194" "https://api.trakt.tv/search/tmdb/$TMDB_ID?type=show" | jq -r ".[0].show.ids.imdb")
+    ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT -- false trakt API response" >> stoday.txt && return
+    ( curl $ARGS --header "Content-Type: application/json" "https://eztv.io/api/get-torrents?imdb_id=" | jq . > "$JUNK/$OUTPUT.tor" ) &
+    # error code for EZTV
+    OMDB_API=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?i=$IMDB_ID&plot=short&apikey=7759dbc7" || exit)
+    grep "Error getting data" <<< "$OMDB_API" && echo "$OUTPUT -- false OMDB API response" >> stoday.txt && return
+    YEAR=$(jq -r '.Year' <<< $OMDB_API); TITLE="$(jq -r ".Title" <<< "$OMDB_API") ($YEAR)"
+    CAST=$(jq -r '.Actors' <<< "$OMDB_API"); GENRE=$(jq -r '.Genre' <<< "$OMDB_API")
+    RATING=$(jq -r '.imdbRating' <<< "$OMDB_API"); PLOT=$(jq -r '.Plot' <<< "$OMDB_API")
+    grep -qiE '(documentary|reality-tv|talk-show)' <<< "$GENRE" && ! grep -q "$OUTPUT" $WHITELIST && return
+    if ! grep -q "$OUTPUT" $WHITELIST; then
+        if [ "$GENRE" == 'N/A' ]; then echo "$OUTPUT -- N/A" >> stoday.txt && return; fi
+    fi
+    #grep -owF "$TITLE" series_list && CROSS_CHECK; break
+    echo "$TITLE" >> today.txt;
+    #sed 's/–/, /'
 
 }
 ARGS='--connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -ks'
 DIR=~/.turbodl; PIXELS=(480 720 1080 2160)
 mkdir -p $DIR/movies $DIR/series $DIR/logs $DIR/junk; cd "$DIR"; JUNK=junk
 find . ! -name 'twitchdl' ! -name '*list' ! -name 'md5' -type f -exec rm -rf {} +
-if [ "$USER" == '' ]; then cat ~/turbodl/whitelist > $DIR/whitelist; cat ~/turbodl/blacklist > $DIR/blacklist; fi
+if [ "$USER" == '' ]; then cat ~/turbodl/list > $DIR/list; fi
 case $1 in
     '')
         URL="https://dl.twitchdl.us/";;
