fixes and improvements

diff --git a/test1 b/test1
--- a/test1
+++ b/test1
@@ -10,6 +10,7 @@ fi
 
 DL_MOVIEDATA(){
 	#function to use when both OMDB and tracktv API fail to get movie details
+	unset IMG2 CAST2 GENRE2 LINKS2
 	if [ ! -e moviedata ]; then
 		wget -q -O moviedata $(grep "$OUTPUT" output2 | grep -o http.*html)		#grab movie page from lightdl
 	fi
@@ -28,13 +29,15 @@ grep ^'<a href=.*html.*title=.*</a>' data | sed "s/'>.*//" > output2	#direct url
 echo -e ""$(date)"\\n--------------------------------" > 'today.txt'
 
 while IFS= read -r OUTPUT; do	#loop through movie titles in output file
-if ! grep -q 'Ambition' <<< "$OUTPUT"; then continue; fi
+#if ! grep -q 'Ambition' <<< "$OUTPUT"; then continue; fi
+	if [ -e moviedata ]; then rm moviedata; fi
 	OUTPUT=$(grep "$OUTPUT" output | sed -e 's/[ ]$//')		#removes spaces if any at the end of titles
 	YEAR=$(grep -oE '[0-9][0-9][0-9][0-9]$' <<< "$OUTPUT")
 	OUTPUT2=$(sed 's/[ -.][0-9][0-9][0-9][0-9]$//' <<< "$OUTPUT")
 	if grep -q "$OUTPUT" 'movie list.txt'; then echo "$OUTPUT   --> already posted" >> 'today.txt'; continue; fi		#skip movies that are already posted
 	OMDB_NAME=$(sed "s/ /%20/g" <<< "$OUTPUT2") #|grep -ioE ^'([a-z].*[a-z]|[0-9].*[a-z]|[a-z].*[0-9]')#format current title by replacing spaces with %20 to work with API's
-	PATTERN=$(sed -e 's/%20//g' -e "s/[ -.]//g" -e 's/\(.\)/\1.*/g' -e 's/..$//' <<< "$OMDB_NAME")		#format title into pattern used in finding download links
+#	PATTERN=$(sed -e 's/%20//g' -e "s/[ -.]//g" -e 's/\(.\)/\1.*/g' -e 's/..$//' <<< "$OMDB_NAME")		#format title into pattern used in finding download links
+
 	if grep -qo '[0-9][0-9][0-9][0-9]' <<< $YEAR; then
 		curl -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?t=$OMDB_NAME&y=$YEAR&type=movie&plot=short&apikey=7759dbc7" | jq "." > "info" 2> /dev/null	#OMDB API to get details of movie
 	else
@@ -42,70 +45,91 @@ if ! grep -q 'Ambition' <<< "$OUTPUT"; then continue; fi
 	fi
 	if grep -qE '("Response": "False"|"Error": "Movie not found!")' info; then
 		curl -s --header "Content-Type: application/json" --header "trakt-api-version: 2" --header "trakt-api-key: 64ba02e985f18ec3a00186209b3605cfbbeedf9890898e3a06b8e020111e8194" "https://api.trakt.tv/search/movie?query=$OMDB_NAME" | jq "." > 'info'  2> /dev/null		#trakttv API, runs when OMDB API fails to get details because of improper title format
-		if grep -q 'imdb' info; then
-			RESULT=$(grep 'imdb":' 'info')
-			while IFS= read -r IMDB_ID; do		#loop through traktv results for imdb ID
-				if grep null <<< "$IMDB_ID"; then
-					continue	#skip current result if imdb ID is null
-				else
-					IMDB_ID=$(sed -e 's/.*: "//' -e 's/",//' <<< "$IMDB_ID")	#get imdb ID if result is not null
-					curl -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?i=$IMDB_ID&plot=short&apikey=7759dbc7" | jq "." > "info" 2> /dev/null	#OMDB API to get movie details with imdb ID when finding with name fails
-					break
-				fi
-			done <<< "$RESULT"
-		else
+		C=0
+		while true; do
+			T=$(cat 'info' | jq -r ".[$C].movie.title")
+			if [ "$T" == null ]; then break; fi
+			Y=$(cat 'info' | jq -r ".[$C].movie.year")
+			if [ "$Y" == $YEAR ]; then
+				IMDB_ID=$(cat 'info' | jq -r ".[$C].movie.ids.imdb")
+				curl -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?i=$IMDB_ID&plot=short&apikey=7759dbc7" | jq "." > "info" 2> /dev/null	#OMDB API to get movie details with imdb ID when finding with name fails
+				break
+			else
+				C=$((C+1))
+			fi
+		done
+		if [ $T == null ]; then
 			DL_MOVIEDATA	#function
-			{
-				echo -e "<div style=\"text-align: center;\">\\n[ NO DESCRIPTION ]\\n\\nIMDB Rating: [ NULL ]\\nCast: $CAST2\\nGenre: [ $GENRE2 ]\\n\\n$LINKS2\\n</div>"
-			} > errors/"$OUTPUT"	#place everything in errors directory because it's incomplete
+			echo -e "<div style=\"text-align: center;\">\\n[ NO DESCRIPTION ]\\n\\nIMDB Rating: [ NULL ]\\nCast: $CAST2\\nGenre: [ $GENRE2 ]\\n\\n$LINKS2\\n</div>" > errors/"$OUTPUT"	#place everything in errors directory because it's incomplete
 			echo "$OUTPUT" >> 'movie list.txt'
 			echo "$OUTPUT   --> error" >> 'today.txt'		#place title in file to upload to dropbox & mail
 			rm moviedata
 			continue
 		fi
+
+#		if grep -q 'imdb' info; then
+#			RESULT=$(grep 'imdb":' 'info')
+#			while IFS= read -r IMDB_ID; do		#loop through traktv results for imdb ID
+#				if grep null <<< "$IMDB_ID"; then
+#					continue	#skip current result if imdb ID is null
+#				else
+#					IMDB_ID=$(sed -e 's/.*: "//' -e 's/",//' <<< "$IMDB_ID")	#get imdb ID if result is not null
+#					curl -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?i=$IMDB_ID&plot=short&apikey=7759dbc7" | jq "." > "info" 2> /dev/null	#OMDB API to get movie details with imdb ID when finding with name fails
+#					break
+#				fi
+#			done <<< "$RESULT"
+#		else
+#			DL_MOVIEDATA	#function
+#			{
+#				echo -e "<div style=\"text-align: center;\">\\n[ NO DESCRIPTION ]\\n\\nIMDB Rating: [ NULL ]\\nCast: $CAST2\\nGenre: [ $GENRE2 ]\\n\\n$LINKS2\\n</div>"
+#			} > errors/"$OUTPUT"	#place everything in errors directory because it's incomplete
+#			echo "$OUTPUT" >> 'movie list.txt'
+#			echo "$OUTPUT   --> error" >> 'today.txt'		#place title in file to upload to dropbox & mail
+#			rm moviedata
+#			continue
+#		fi
 	fi
 
 	#execute if OMDB API is successful
-	A=$(grep "Title" 'info' | sed -e 's/.*: "//' -e 's/",//')	#get title
-	B=$(grep "Year.*:" 'info' | sed -e 's/.*: "//' -e 's/",//')		#get year
-	TITLE="$A ($B)"		#format title and year
-	IMG=$(grep "Poster" 'info' | sed -e 's/.*: "//' -e 's/",//')	#get image URL
-	if grep -q 'N/A' <<< "$IMG"; then DL_MOVIEDATA && IMG="$IMG2"; fi	#try to get image URL from DL_MOVIEDATA function if image URL is N/A
-	#write code to check dimension of image
-	#curl -s "$IMG" -o movies/"$TITLE".jpg
-	PLOT=$(grep "Plot" 'info' | sed -e 's/.*: "//' -e 's/",//')		#get movie plot
 	RATING=$(grep "imdbRating" 'info' | sed -e 's/.*: "//' -e 's/",//')		#get movie rating
 	if [ "$RATING" != 'N/A' ]; then
 		RATE=$(sed 's/\.//' <<< "$RATING")
 		if [ $RATE -lt 55 ]; then continue; fi	#skip movie if rating is below 5.5
-#	else
-#		echo "$OUTPUT" >> 'movie list.txt'
-#		echo "$OUTPUT   --> error" >> 'today.txt'		#place title in file to upload to dropbox & mail
-#		continue
+	else
+		echo "$OUTPUT" >> 'movie list.txt'
+		echo "$OUTPUT   --> error" >> 'today.txt'		#place title in file to upload to dropbox & mail
 	fi
-	CAST=$(grep "Actors" 'info' | sed -e 's/.*: "//' -e 's/",//')		#get cast
-	if grep -q 'N/A' <<< "$CAST"; then DL_MOVIEDATA && CAST=$(sed 's/Cast: //' <<< "$CAST2"); fi	#try to get cast from DL_MOVIEDATA function if cast is N/A
 	GENRE=$(grep "Genre" 'info' | sed -e 's/.*: "//' -e 's/",//')	#get genre
 	if grep -q 'N/A' <<< "$GENRE"; then DL_MOVIEDATA && GENRE="$GENRE2"; fi		#try to get genre from DL_MOVIEDATA function if genre is N/A
 	if grep -qi 'documentary' <<< "$GENRE"; then continue; fi	#skip documentaries
-	LINKS=$(grep -iE ^"<span style=\"font-family.*<a href=.*>$PATTERN.*a>" data | sed -e "s/.*<a/<a/" -e "s/a>.*/a>/")		#get download links
-	if ! grep -qE 'mkv' <<< "$LINKS"; then
-		wget -q -O moviedata $(grep "$OUTPUT" output2 | grep -o http.*html)		#grab movie page from lightdl
-		LINKS=$(grep ^"<span style=\"font-family.*http.*a>" moviedata | sed -e "s/.*<a/<a/" -e "s/a>.*/a>/")	#alternative if download links returns empty
-		rm moviedata
-	fi
+	A=$(grep "Title" 'info' | sed -e 's/.*: "//' -e 's/",//')	#get title
+	B=$(grep "Year.*:" 'info' | sed -e 's/.*: "//' -e 's/",//')		#get year
+	TITLE="$A ($B)"		#format title and year
+	PLOT=$(grep "Plot" 'info' | sed -e 's/.*: "//' -e 's/",//')		#get movie plot
+	CAST=$(grep "Actors" 'info' | sed -e 's/.*: "//' -e 's/",//')		#get cast
+	if grep -q 'N/A' <<< "$CAST"; then DL_MOVIEDATA && CAST=$(sed 's/Cast: //' <<< "$CAST2"); fi	#try to get cast from DL_MOVIEDATA function if cast is N/A
+	#LINKS=$(grep -iE ^"<span style=\"font-family.*<a href=.*>$PATTERN.*a>" data | sed -e "s/.*<a/<a/" -e "s/a>.*/a>/")		#get download links
+	LINKS=$(wget -q -O - $(grep "$OUTPUT" output2 | grep -o http.*html) | grep ^"<span style=\"font-family.*http.*a>" | sed -e "s/.*<a/<a/" -e "s/a>.*/a>/")	#grab movie page from lightdl & grep links
 	#if grep -qiE "(cam|hdts|hdtc)"
-	{
-		echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\n$LINKS\\n</div>\\n\\nTags: $GENRE, $B"
-	} > movies/"$OUTPUT"
+	CHECK=$(echo -e "$A\\n$B\\n$RATING\\n$GENRE" | grep -o 'N/A' || echo 'A/N')
+	if grep -q 'N/A' <<< "$CHECK"; then
+		echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\n$LINKS\\n</div>\\n\\nTags: $GENRE, $B" > errors/"$OUTPUT"
+		continue
+	else
+		IMG=$(grep "Poster" 'info' | sed -e 's/.*: "//' -e 's/",//')	#get image URL
+		if grep -q 'N/A' <<< "$IMG"; then DL_MOVIEDATA && IMG="$IMG2"; fi	#try to get image URL from DL_MOVIEDATA function if image URL is N/A
+		#write code to check dimension of image
+		curl -s "$IMG" -o movies/"$OUTPUT".jpg
+		echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\n$LINKS\\n</div>\\n\\nTags: $GENRE, $B" > movies/"$OUTPUT"
+	fi
 	echo "$OUTPUT" | tee -a 'movie list.txt' 'today.txt'		#place title in file to upload to dropbox & mail
-if grep -q 'Ambition' <<< "$OUTPUT"; then break; fi
+	echo | mutt -s "$TITLE" -i movies/"$OUTPUT" -a movies/"$OUTPUT".jpg -- persiejulius7@gmail.com
+#if grep -q 'Ambition' <<< "$OUTPUT"; then break; fi
 done < output	#end of loop
 
 #curl -s -X POST https://content.dropboxapi.com/2/files/upload --header "Authorization: Bearer DlS2vDBOAr4AAAAAAAABck-oi1CylO-l-Dg6lddfRy4vcq5iH8WJxU6jNkK__uGY" --header "Dropbox-API-Arg: {\"path\": \"/dev/movie list.txt\",\"mode\": \"overwrite\",\"autorename\": false,\"mute\": false,\"strict_conflict\": false}" --header "Content-Type: application/octet-stream" --data-binary @'movie list.txt' > /dev/null		#upload titles file to dropbox
-if [ -e moviedata ]; then rm moviedata; fi
-#if [ -z "$(ls -A errors)" ]; then
-#	echo | mutt -s 'turbodlbot' -i 'today.txt' -- sgm4kv@gmail.com info@turbodl.xyz
-#else
-#	echo | mutt -s 'turbodlbot' -i 'today.txt' -a errors/* -- sgm4kv@gmail.com info@turbodl.xyz
-#fi
+if [ -z "$(ls -A errors)" ]; then
+	echo | mutt -s 'turbodlbot' -i 'today.txt' -- persiejulius7@gmail.com info@turbodl.xyz
+else
+	echo | mutt -s 'turbodlbot' -i 'today.txt' -a errors/* -- persiejulius7@gmail.com info@turbodl.xyz
+fi
