fixes and improvements

diff --git a/test b/test
--- a/test
+++ b/test
@@ -9,9 +9,9 @@ else
 	mkdir -p ~/.tmp/movies ~/.tmp/errors; cd ~/.tmp
 fi
 
-exec 3>&1 4>&2
-trap 'exec 2>&4 1>&3' 0 1 2 3
-exec 1>logs.txt 2>&1
+#exec 3>&1 4>&2
+#trap 'exec 2>&4 1>&3' 0 1 2 3
+#exec 1>logs.txt 2>&1
 set -ex
 
 DL_MOVIEDATA(){
@@ -28,8 +28,23 @@ DL_MOVIEDATA(){
 	export IMG2 CAST2 GENRE2 LINKS2		#export variables to use outside the function
 }
 
+#curl -s -X POST https://content.dropboxapi.com/2/files/download --header "Authorization: Bearer DlS2vDBOAr4AAAAAAAABck-oi1CylO-l-Dg6lddfRy4vcq5iH8WJxU6jNkK__uGY" --header "Dropbox-API-Arg: {\"path\": \"/dev/movie list.txt\"}" > 'movie list.txt'		#download list of movies from dropbox
+#get movies posted to website
+COUNT=1; COUNT1=0
+echo '---script starts above this---' > 'movie list.txt'
+while true; do
+	curl -s -X GET "https://turbodl.xyz/wp-json/wp/v2/posts?page=$COUNT&per_page=24" > file.x
+	if grep -q 'rest_post_invalid_page_number' file.x; then break; fi
+	while [ $COUNT1 -lt 24 ]; do
+		title=$(cat file.x | jq -r ".[$COUNT1].title.rendered" | sed -e 's/&#8211;/-/g' -e "s/&#8217;/'/g" -e "s/&#038;/\&/g" -e "s/&#8216;/'/g" -e 's/&#822[0-1];/"/g' -e 's/&amp;/\&/g')
+		if [ "$title" == null ]; then break; fi
+		echo "$title" >> 'movie list.txt'
+		COUNT1=$((COUNT1+1))
+	done
+	COUNT1=0; COUNT=$((COUNT+1))
+done
+
 wget -q -O data "https://lightdlmovies.blogspot.com/search/label/MOVIES"		#download lightdl movies page
-curl -s -X POST https://content.dropboxapi.com/2/files/download --header "Authorization: Bearer DlS2vDBOAr4AAAAAAAABck-oi1CylO-l-Dg6lddfRy4vcq5iH8WJxU6jNkK__uGY" --header "Dropbox-API-Arg: {\"path\": \"/dev/movie list.txt\"}" > 'movie list.txt'		#download list of movies from dropbox
 grep ^'<a href=.*html.*title=.*</a>' data | sed -e "s/'>.*//" -e "s/.*title='//" -e "s/<\/a>//" > output	#direct titles of movies into output file
 grep ^'<a href=.*html.*title=.*</a>' data | sed "s/'>.*//" > output2	#direct urls of movies into output2 file
 echo -e ""$(date)"\\n--------------------------------" > 'today.txt'
@@ -40,7 +55,11 @@ while IFS= read -r OUTPUT; do	#loop through movie titles in output file
 	OUTPUT=$(grep "$OUTPUT" output | sed -e 's/[ ]$//')		#removes spaces if any at the end of titles
 	YEAR=$(grep -oE '[0-9][0-9][0-9][0-9]$' <<< "$OUTPUT")
 	OUTPUT2=$(sed 's/[ -.][0-9][0-9][0-9][0-9]$//' <<< "$OUTPUT")
-	if grep -q ^"$OUTPUT" 'movie list.txt'; then echo "$OUTPUT   --> already posted" >> 'today.txt'; continue; fi		#skip movies that are already posted
+	if grep -q "$OUTPUT2.*$YEAR" 'movie list.txt'; then echo "$OUTPUT   --> already posted" >> 'today.txt'; continue; fi		#skip movies that are already posted
+	if grep -q '&' <<< "$OUTPUT2"; then
+		OUTPUT3=$(sed 's/\&/and/' <<< "$OUTPUT2")
+		if grep -q "$OUTPUT3.*$YEAR" 'movie list.txt'; then echo "$OUTPUT   --> already posted" >> 'today.txt'; continue; fi
+	fi
 	OMDB_NAME=$(sed "s/ /%20/g" <<< "$OUTPUT2") #|grep -ioE ^'([a-z].*[a-z]|[0-9].*[a-z]|[a-z].*[0-9]')#format current title by replacing spaces with %20 to work with API's
 #	PATTERN=$(sed -e 's/%20//g' -e "s/[ -.]//g" -e 's/\(.\)/\1.*/g' -e 's/..$//' <<< "$OMDB_NAME")		#format title into pattern used in finding download links
 
@@ -67,7 +86,7 @@ while IFS= read -r OUTPUT; do	#loop through movie titles in output file
 		if [ "$T" == null ]; then
 			DL_MOVIEDATA	#function
 			echo -e "<div style=\"text-align: center;\">\\n[ NO DESCRIPTION ]\\n\\nIMDB Rating: [ NULL ]\\nCast: $CAST2\\nGenre: [ $GENRE2 ]\\n\\n$LINKS2\\n</div>\\n\\nTags: [ $GENRE2, $YEAR ]" > errors/"$OUTPUT"	#place everything in errors directory because it's incomplete
-			echo "$OUTPUT" >> 'movie list.txt'
+			sed -i "1s/^/$OUTPUT\\n/" 'movie list.txt'
 			echo "$OUTPUT   --> incomplete" >> 'today.txt'		#place title in file to upload to dropbox & mail
 			rm moviedata
 			continue
@@ -102,7 +121,6 @@ while IFS= read -r OUTPUT; do	#loop through movie titles in output file
 		RATE=$(sed 's/\.//' <<< "$RATING")
 		if [ $RATE -lt 55 ]; then echo "$OUTPUT   --> rating: $RATING" >> 'today.txt'; continue; fi	#skip movie if rating is below 5.5
 	else
-		echo "$OUTPUT" >> 'movie list.txt'
 		echo "$OUTPUT   --> rating: $RATING" >> 'today.txt'		#place title in file to upload to dropbox & mail
 	fi
 	GENRE=$(grep "Genre" 'info' | sed -e 's/.*: "//' -e 's/",//')	#get genre
@@ -119,6 +137,7 @@ while IFS= read -r OUTPUT; do	#loop through movie titles in output file
 	#if grep -qiE "(camrip|hdts|hdtc)"
 	CHECK=$(echo -e "$A\\n$B\\n$RATING\\n$GENRE" | grep -o 'N/A' || echo 'A/N')
 	if grep -q 'N/A' <<< "$CHECK"; then
+		sed -i "1s/^/$OUTPUT\\n/" 'movie list.txt'
 		echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\n$LINKS\\n</div>\\n\\nTags: $GENRE, $B" > errors/"$OUTPUT"
 		continue
 	else
@@ -142,11 +161,11 @@ while IFS= read -r OUTPUT; do	#loop through movie titles in output file
 			echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\n$LINKS\\n</div>\\n\\nTags: $GENRE, $B" > errors/"$OUTPUT"
 			continue
 		else
+			sed -i "1s/^/$TITLE\\n/" 'movie list.txt'
+			echo "$TITLE" >> 'today.txt'		#place title in file to upload to dropbox & mail
 			echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\n$LINKS\\n</div>\\n\\nTags: $GENRE, $B" > movies/"$OUTPUT"
 		fi
 	fi
-	sed -i "1s/^/$TITLE\\n/" 'movie list.txt'
-	echo "$TITLE" >> 'today.txt'		#place title in file to upload to dropbox & mail
 	if [ "$USER" != persie ]; then
 	echo | mutt -s "$TITLE" -i movies/"$OUTPUT" -a movies/"$OUTPUT".jpg -- Ud37asAUd8a7@turbodl.xyz
 	fi
@@ -155,9 +174,9 @@ done < output	#end of loop
 #curl -s -X POST https://content.dropboxapi.com/2/files/upload --header "Authorization: Bearer DlS2vDBOAr4AAAAAAAABck-oi1CylO-l-Dg6lddfRy4vcq5iH8WJxU6jNkK__uGY" --header "Dropbox-API-Arg: {\"path\": \"/dev/movie list.txt\",\"mode\": \"overwrite\",\"autorename\": false,\"mute\": false,\"strict_conflict\": false}" --header "Content-Type: application/octet-stream" --data-binary @'movie list.txt' > /dev/null		#upload titles file to dropbox
 if [ "$USER" != persie ]; then
 if [ -z "$(ls -A errors)" ]; then
-	echo | mutt -s 'turbodlbot' -i 'today.txt' -a 'movie list.txt' -- persie@turbodl.xyz 'info@turbodl.xyz'
+	echo | mutt -s 'turbodlbot' -i 'today.txt' -- persie@turbodl.xyz 'info@turbodl.xyz'
 else
-	echo | mutt -s 'turbodlbot' -i 'today.txt' -a errors/* 'movie list.txt' -- persie@turbodl.xyz 'info@turbodl.xyz'
+	echo | mutt -s 'turbodlbot' -i 'today.txt' -a errors/* -- persie@turbodl.xyz 'info@turbodl.xyz'
 fi
-echo | mutt -s 'turbodlbot logs' -a logs.txt -- persie@turbodl.xyz
+echo | mutt -s 'turbodlbot log' -a logs.txt 'movie list.txt' -- persie@turbodl.xyz
 fi
