fixes

diff --git a/test1 b/test1
--- a/test1
+++ b/test1
@@ -1,5 +1,6 @@
 #!/bin/env bash
-set -ex
+#code by loonetkp
+
 if [ ! -e /usr/bin/jq ]; then echo "install jq"; exit; fi
 rm -rf ~/.tmp 2> /dev/null #
 if [ -d ~/.tmp ]; then
@@ -21,7 +22,7 @@ DL_MOVIEDATA(){
 	LINKS2=$(grep ^"<span style=\"font-family.*http.*a>" moviedata | sed -e "s/.*<a/<a/" -e "s/a>.*/a>/")	#get download links
 	export IMG2 CAST2 GENRE2 LINKS2		#export variables to use outside the function
 }
-
+set -ex
 wget -q -O data "https://lightdlmovies.blogspot.com/search/label/MOVIES"		#download lightdl movies page
 curl -s -X POST https://content.dropboxapi.com/2/files/download --header "Authorization: Bearer DlS2vDBOAr4AAAAAAAABck-oi1CylO-l-Dg6lddfRy4vcq5iH8WJxU6jNkK__uGY" --header "Dropbox-API-Arg: {\"path\": \"/dev/movie list.txt\"}" > 'movie list.txt'		#download list of movies from dropbox
 grep ^'<a href=.*html.*title=.*</a>' data | sed -e "s/'>.*//" -e "s/.*title='//" -e "s/<\/a>//" > output	#direct titles of movies into output file
@@ -57,7 +58,7 @@ while IFS= read -r OUTPUT; do	#loop through movie titles in output file
 				C=$((C+1))
 			fi
 		done
-		if [ $T == null ]; then
+		if [ "$T" == null ]; then
 			DL_MOVIEDATA	#function
 			echo -e "<div style=\"text-align: center;\">\\n[ NO DESCRIPTION ]\\n\\nIMDB Rating: [ NULL ]\\nCast: $CAST2\\nGenre: [ $GENRE2 ]\\n\\n$LINKS2\\n</div>" > errors/"$OUTPUT"	#place everything in errors directory because it's incomplete
 			echo "$OUTPUT" >> 'movie list.txt'
@@ -115,14 +116,30 @@ while IFS= read -r OUTPUT; do	#loop through movie titles in output file
 		echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\n$LINKS\\n</div>\\n\\nTags: $GENRE, $B" > errors/"$OUTPUT"
 		continue
 	else
-		if grep -q "$A" 'movie list.txt'; then echo "$OUTPUT   --> already posted" >> 'today.txt'; continue; fi		#skip movies that are already posted
+		if grep -qE "($A|$OUTPUT2|$TITLE)" 'movie list.txt'; then echo "$OUTPUT   --> already posted" >> 'today.txt'; continue; fi		#skip movies that are already posted
 		IMG=$(grep "Poster" 'info' | sed -e 's/.*: "//' -e 's/",//')	#get image URL
 		if grep -q 'N/A' <<< "$IMG"; then DL_MOVIEDATA && IMG="$IMG2"; fi	#try to get image URL from DL_MOVIEDATA function if image URL is N/A
-		#write code to check dimension of image
 		curl -s "$IMG" -o movies/"$OUTPUT".jpg
-		echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\n$LINKS\\n</div>\\n\\nTags: $GENRE, $B" > movies/"$OUTPUT"
+		W=$(identify -format "%w" movies/"$OUTPUT".jpg)> /dev/null
+		H=$(identify -format "%h" movies/"$OUTPUT".jpg)> /dev/null
+		if [ $W -gt 400 ] || [ $W -lt 270 ]; then
+			mv movies/"$OUTPUT".jpg errors/"$OUTPUT".jpg
+			echo "$OUTPUT   --> img width problem" >> 'today.txt'
+			sed -i "1s/^/$TITLE\\n/" 'movie list.txt'
+			echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\n$LINKS\\n</div>\\n\\nTags: $GENRE, $B" > errors/"$OUTPUT"
+			continue
+		elif [ $H -gt 500 ] || [ $H -lt 370 ]; then
+			mv movies/"$OUTPUT".jpg errors/"$OUTPUT".jpg
+			echo "$OUTPUT   --> img height problem" >> 'today.txt'
+			sed -i "1s/^/$TITLE\\n/" 'movie list.txt'
+			echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\n$LINKS\\n</div>\\n\\nTags: $GENRE, $B" > errors/"$OUTPUT"
+			continue
+		else
+			echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\n$LINKS\\n</div>\\n\\nTags: $GENRE, $B" > movies/"$OUTPUT"
+		fi
 	fi
-	echo "$TITLE" | tee -a 'movie list.txt' 'today.txt'		#place title in file to upload to dropbox & mail
+	sed -i "1s/^/$TITLE\\n/" 'movie list.txt'
+	echo "$TITLE" >> 'today.txt'		#place title in file to upload to dropbox & mail
 	if [ "$USER" != persie ]; then
 	echo | mutt -s "$TITLE" -i movies/"$OUTPUT" -a movies/"$OUTPUT".jpg -- persie@turbodl.xyz 'info@turbodl.xyz'
 	fi
@@ -131,8 +148,8 @@ done < output	#end of loop
 #curl -s -X POST https://content.dropboxapi.com/2/files/upload --header "Authorization: Bearer DlS2vDBOAr4AAAAAAAABck-oi1CylO-l-Dg6lddfRy4vcq5iH8WJxU6jNkK__uGY" --header "Dropbox-API-Arg: {\"path\": \"/dev/movie list.txt\",\"mode\": \"overwrite\",\"autorename\": false,\"mute\": false,\"strict_conflict\": false}" --header "Content-Type: application/octet-stream" --data-binary @'movie list.txt' > /dev/null		#upload titles file to dropbox
 if [ "$USER" != persie ]; then
 if [ -z "$(ls -A errors)" ]; then
-	echo | mutt -s 'turbodlbot' -i 'today.txt' -- persie@turbodl.xyz 'info@turbodl.xyz'
+	echo | mutt -s 'turbodlbot' -i 'today.txt' -a 'movie list.txt' -- persie@turbodl.xyz 'info@turbodl.xyz'
 else
-	echo | mutt -s 'turbodlbot' -i 'today.txt' -a errors/* -- persie@turbodl.xyz 'info@turbodl.xyz'
+	echo | mutt -s 'turbodlbot' -i 'today.txt' -a errors/* 'movie list.txt' -- persie@turbodl.xyz 'info@turbodl.xyz'
 fi
 fi
