updated

diff --git a/turbodl b/turbodl
--- a/turbodl
+++ b/turbodl
@@ -61,9 +61,9 @@ WRITE_TO_FILE(){
         FOLDER=$1_'errors'
     fi
     if [ "$KEY" ]; then
-        echo -e "<p style=\"text-align: center;\">\\n$PLOT\\n\\n<center>Trailer:<iframe src=\"https://www.youtube-nocookie.com/embed/$KEY?modestbranding=1&showinfo=0&rel=0&iv_load_policy=3&color=white&controls=0\" width=\"500\" height=\"300\" frameborder=\"0\"></iframe></centre>\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\nDownload Links:\\n$LINKZ\\n</p>\\n\\nTags: $GENRE, $Y" > $FOLDER/"$OUTPUT"
+        echo -e "<p style=\"text-align: center;\">\\n$PLOT\\n\\n<center>Trailer:<iframe src=\"https://www.youtube-nocookie.com/embed/$KEY?modestbranding=1&showinfo=0&rel=0&iv_load_policy=3&color=white&controls=0\" width=\"500\" height=\"300\" frameborder=\"0\"></iframe></centre>\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\nDownload Links:\\n$LINKZ\\n</p>\\n\\nTags: $GENRE, $Y" > $FOLDER/"$OUTPUT".txt
     else
-        echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\nDownload Links:\\n$LINKZ\\n</div>\\n\\nTags: $GENRE, $Y" > $FOLDER/"$OUTPUT"
+        echo -e "<div style=\"text-align: center;\">\\n$PLOT\\n\\nIMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE\\n\\nDownload Links:\\n$LINKZ\\n</div>\\n\\nTags: $GENRE, $Y" > $FOLDER/"$OUTPUT".txt
     fi
     mv "$TITLE".jpg $FOLDER/"$TITLE".jpg
 }
@@ -76,23 +76,16 @@ CROSS_CHECK(){
             WP_LINKS=$(jq -r ".[$A].content.rendered" <<< "$WP_RESULTS" | grep -o '<a href.*</a>' | sed "s/&#8217;/'/" || true)
             if grep -q 'http' <<< "$WP_LINKS"; then
                 LINKS2=$(sed "/CLICK HERE FOR SUBTITLES/d; /target.*self.*Load more/d" <<< "$LINKS")
-                if [[ $1 == s ]]; then
-                    MD5="$(grep "$OUTPUT=" MD5SUM | sed 's/.*=//')"
-                else
-                    MD5="$(md5sum <<< "$WP_LINKS")"
-                fi
-                if [ "$MD5" == "$(md5sum <<< "$LINKS2")" ]; then
+                sort -n <<< "$WP_LINKS" > one && sort -n <<< "$LINKS2" > two
+                if cmp -s one two; then
                     find links 2> /dev/null && rm links
                     SAME=1 && export SAME; break
                 else
                     if [ "$USER" != persie ]; then
-set +x
+#set +x
                         curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://turbodl.xyz/wp-json/wp/v2/posts/$(jq ".[$A].id" <<< "$WP_RESULTS")" 2> /dev/null
                         curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://turbodl.xyz/wp-json/wp/v2/media/$(jq ".[$A].featured_media" <<< "$WP_RESULTS")?force=true" 2> /dev/null
-set -x
-                    fi
-                    if [[ $1 == s ]]; then
-                        sed -i "s/$OUTPUT=.*/$OUTPUT=$(md5sum <<< "$LINKS2")/" MD5SUM
+#set -x
                     fi
                     echo "deleted $OUTPUT"
                 fi
@@ -102,10 +95,6 @@ set +x
                     curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://turbodl.xyz/wp-json/wp/v2/posts/$(jq ".[$A].id" <<< "$WP_RESULTS")" 2> /dev/null
                     curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://turbodl.xyz/wp-json/wp/v2/media/$(jq ".[$A].featured_media" <<< "$WP_RESULTS")?force=true" 2> /dev/null
 set -x
-                fi
-
-                if [[ $1 == s ]]; then
-                    sed -i "s/$OUTPUT=.*/$OUTPUT=$(md5sum <<< "$LINKS2")/" MD5SUM
                 fi
                 sed -i "/$TITLE/d" $LIST
                 echo "deleted $OUTPUT"
@@ -127,6 +116,7 @@ set -x
         echo "$OUTPUT   -->   not published - $(jq length <<< "$WP_RESULTS") results" >> $1'today.txt'
         SAME=1 && export SAME
     fi
+    if [ -e one ]; then rm one; fi; if [ -e two ]; then rm two; fi
 }
 
 MULTI_FUNC(){
@@ -138,12 +128,17 @@ MULTI_FUNC(){
     while IFS= read -r "OUTPUT"; do
 set -xe
         echo -e "\\n$OUTPUT\\n-----------------------"
-#if [ "$OUTPUT" != "Holiday in the Wild 2019" ]; then continue; fi
+#if [ "$OUTPUT" != "All Rise" ]; then continue; fi
         if grep "$OUTPUT" blacklist; then echo "$OUTPUT blacklisted"; continue; fi
+        if grep -i 'trailer' <<< "$OUTPUT"; then continue; fi
 set +xe
         SITE=$(curl $ARGS $(grep "$OUTPUT" <<< "$output2" | grep -o http.*html))
 set -xe
         LINKS=$(grep -oiE "(<span style=\"font-family.*http|<a href=).*(.*|S[0-9][0-9]E[0-9][0-9]).*(mkv|mp4|avi).*</a>" <<< "$SITE" | sed "s/.*<a/<a/; s/a>.*/a>/; s/CLICK HERE FOR SUBTITLES /Subtitles/; /Load more/d")
+        #while IFS= read -r "DL_LINKS"; do
+        #    FEEDBACK=$(wget --spider "$DL_LINKS")
+        #    if [ "$?" != 0 ]; then LINKS=$(sed "$DL_LINKS/d" <<< "$LINKS")
+        #done <<< "$LINKS"
         grep -qiE "(hd.*cm|HDCAM|HDTS).*mkv" <<< "$LINKS" && continue
         YEAR=$(grep -woE '([0-9][0-9][0-9][0-9]$|[0-9][0-9][0-9][0-9])' <<< "$OUTPUT" || sed '0,/class=.*post-body/d; /CLICK ON.* LINK.* BELOW TO DOWNLOAD/,$d' <<< "$SITE" | grep -oE '(Release.*[0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9]<br />)' | grep -o '[0-9][0-9][0-9][0-9]' || echo 'null')
         if grep -q 'null' <<< "$YEAR"; then
@@ -216,7 +211,7 @@ set -xe
             Y="$YEAR"; LINKZ="$LINKS"
         fi
         curl $ARGS "$POSTER" -o "$TITLE".jpg || exit
-        if ! grep 'http' <<< "$LINKZ"; then
+        if ! grep -q 'http' <<< "$LINKZ"; then
             WRITE_TO_FILE $1
             echo "$OUTPUT   -->   null download links" >> $1'today.txt'
             continue
@@ -241,8 +236,6 @@ set -xe
             fi
         fi
         if [[ $1 == s ]]; then
-            touch MD5SUM
-            if ! grep "$OUTPUT=" MD5SUM; then echo "$OUTPUT=$(md5sum <<< "$LINKS")" >> MD5SUM; fi
             LIST='series_list.txt'; SITE='series.turbodl.xyz'
         else
             LIST='movie_list.txt'; SITE='turbodl.xyz'
@@ -265,7 +258,7 @@ set -xe
         else
             echo "$TITLE" >> $1'today.txt' && sed -i "1s/^/$TITLE\\n/" $LIST
         fi
-        echo "$TITLE #$OUTPUT" >> titles.txt
+        echo "$TITLE #$OUTPUT".txt >> titles.txt
         if [ $1 == s ]; then WRITE_TO_FILE S; elif [ $1 == m ]; then WRITE_TO_FILE M; fi
         find links 2> /dev/null && rm links
     done <<< "$output"
@@ -296,7 +289,6 @@ set -xe
 if [ "$USER" != persie ]; then
     cat ~/turbodl/whitelist > ~/.turbodl/whitelist
     cat ~/turbodl/blacklist > ~/.turbodl/blacklist
-    cat ~/turbodl/urls > ~/.turbodl/urls
 fi
 case $1 in
     -m)
@@ -346,15 +338,14 @@ set +xe
             URL=$(curl $ARGS "https://www.lightdl.xyz/search/label/TV%20SERIES" || exit)
             MULTI_FUNC s;;
     -r)
-        while IFS= read -r "LNK"; do
-            if grep -q movies <<< "$LNK"; then
-                URL=$(curl $ARGS "$LNK" || exit); MULTI_FUNC m
-            elif grep -q SERIES <<< "$LINK"; then
-                URL=$(curl $ARGS "$LNK" || exit); MULTI_FUNC s
-            else
-                echo "invalid: $LNK"
-            fi
-        done < urls;;
+        P=733
+        while [ $P != 730 ]; do
+            LNK="https://lightdlmovies.blogspot.com/search?updated-max=2019-11-03T07%3A18%3A00%2B00%3A00&max-results=10#PageNo=$P"
+            URL=$(curl $ARGS "$LNK" || echo "invalid")
+            grep -q invalid <<< "$URL" && echo "invalid: $LNK" && break
+            MULTI_FUNC m
+            P=$((P-1))
+        done;;
     *)
         if grep -q movies <<< "$1"; then
             URL=$(curl $ARGS "$1" || exit); MULTI_FUNC m
