updated

diff --git a/turbodl b/turbodl
--- a/turbodl
+++ b/turbodl
@@ -89,8 +89,8 @@ WRITE_TO_FILE(){
     if [ -e links ]; then LINKZ=$(cat links); fi
     if [ "$KEY" ]; then
         echo -e "<p style=\"text-align: center;\">\\n$PLOT\\n\\n<center>Trailer:\\n<iframe src=\"https://www.youtube-nocookie.com/embed/$KEY?modestbranding=1&showinfo=0&rel=0&iv_load_policy=3&color=white&controls=0\" width=\"500\" height=\"300\" frameborder=\"0\"></iframe></centre></p>\\n\\n<p style=\"text-align: center;\">IMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE</p>\\n\\n<p style=\"text-align: center;\">Download Links:\\n$LINKZ\\n</p>\\n\\nTags: $GENRE, $Y" > $FOLDER/"$OUTPUT".txt
-    elif [ $COLLECTION ]; then
-        echo -e "<p style=\"text-align: center;\">Genre: $GENRE</p>\\n\\n<p style=\"text-align: center;\">Download Links:\\n$LINKZ\\n</p>\\n\\nTags: $GENRE, $Y" > $FOLDER/"$OUTPUT".txt
+    #elif [ $COLLECTION ]; then
+    #    echo -e "<p style=\"text-align: center;\">\\n$PLOT\\n\\nGenre: $GENRE</p>\\n\\n<p style=\"text-align: center;\">Download Links:\\n$LINKZ\\n</p>\\n\\nTags: $GENRE, $Y" > $FOLDER/"$OUTPUT".txt
     else
         echo -e "<p style=\"text-align: center;\">\\n$PLOT</p>\\n\\n<p style=\"text-align: center;\">IMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE</p>\\n\\n<p style=\"text-align: center;\">Download Links:\\n$LINKZ\\n</p>\\n\\nTags: $GENRE, $Y" > $FOLDER/"$OUTPUT".txt
     fi
@@ -224,24 +224,28 @@ set -xe
             else
                 unset KEY
             fi
-            if [[ $1 == s ]]; then N='show'; else N='movie'; fi
-            IMDB_ID=$(curl $ARGS --header "Content-Type: application/json" --header "trakt-api-version: 2" --header "trakt-api-key: 64ba02e985f18ec3a00186209b3605cfbbeedf9890898e3a06b8e020111e8194" "https://api.trakt.tv/search/tmdb/$TMDB_ID?type=$N" | jq -r ".[0].$N.ids.imdb")
-            ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT   -->   IMDB error getting data" >> $1'today.txt' && continue
-            OMDB_API=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?i=$IMDB_ID&plot=short&apikey=7759dbc7" || exit)
-            grep "Error getting data" <<< "$OMDB_API" && echo "$OUTPUT   -->   OMDB error getting data" >> $1'today.txt' && continue
-            YEAR=$(jq -r '.Year' <<< $OMDB_API); TITLE="$(jq -r ".Title" <<< "$OMDB_API") ($YEAR)"
-            PLOT=$(jq -r '.Plot' <<< "$OMDB_API"); grep -q 'N/A' <<< "$PLOT" && PLOT="$OVERVIEW"
+        fi
+        if [[ $1 == s ]]; then N='show'; else N='movie'; fi
+        IMDB_ID=$(curl $ARGS --header "Content-Type: application/json" --header "trakt-api-version: 2" --header "trakt-api-key: 64ba02e985f18ec3a00186209b3605cfbbeedf9890898e3a06b8e020111e8194" "https://api.trakt.tv/search/tmdb/$TMDB_ID?type=$N" | jq -r ".[0].$N.ids.imdb")
+        ! grep -q 'tt' <<< "$IMDB_ID" && echo "$OUTPUT   -->   IMDB error getting data" >> $1'today.txt' && continue
+        OMDB_API=$(curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s -H "Accept: application/json" -H "Content-Type: application/json" "http://www.omdbapi.com/?i=$IMDB_ID&plot=short&apikey=7759dbc7" || exit)
+        grep "Error getting data" <<< "$OMDB_API" && echo "$OUTPUT   -->   OMDB error getting data" >> $1'today.txt' && continue
+        if [ $COLLECTION ]; then
+            TITLE="$NAME - Collection"; GENRE='Collection'; unset KEY
+            CAST=N/A; RATING=N/A
+        else
+            YEAR=$(jq -r '.Year' <<< $OMDB_API)
+            TITLE="$(jq -r ".Title" <<< "$OMDB_API") ($YEAR)"
             CAST=$(jq -r '.Actors' <<< "$OMDB_API"); GENRE=$(jq -r '.Genre' <<< "$OMDB_API")
             if grep -qiE '(documentary|reality-tv)' <<< "$GENRE"; then if ! grep -q "$OUTPUT" whitelist; then continue; fi; fi
             RATING=$(jq -r '.imdbRating' <<< "$OMDB_API")
-            if [[ $1 == s ]]; then PARSE; fi
-            if [[ $1 == s ]]; then
-                Y=$(sed 's/–/, /' <<< $YEAR); LINKZ=$(cat links)
-            else
-                Y="$YEAR"; LINKZ="$LINKS"
-            fi
+        fi
+        PLOT=$(jq -r '.Plot' <<< "$OMDB_API"); grep -q 'N/A' <<< "$PLOT" && PLOT="$OVERVIEW"
+        if [[ $1 == s ]]; then PARSE; fi
+        if [[ $1 == s ]]; then
+            Y=$(sed 's/–/, /' <<< $YEAR); LINKZ=$(cat links)
         else
-            TITLE="$NAME - Collection"; GENRE='Collection'; unset KEY
+            Y="$YEAR"; LINKZ="$LINKS"
         fi
         curl $ARGS "$POSTER" -o "$TITLE".jpg || exit
         if [ ! $COLLECTION ]; then
