updated

diff --git a/turbodl b/turbodl
--- a/turbodl
+++ b/turbodl
@@ -7,7 +7,7 @@ BLACKLIST(){
     fi
 }
 PARSE(){
-set +x
+set +xe
     touch links; D=1
     while true; do
         if [ $D -gt 9 ]; then TAG="s$D"; else TAG="S0$D"; fi
@@ -20,10 +20,10 @@ set +x
         done
         D=$((D+1))
     done
-set -x
+set -xe
 }
 GET_SIZES(){
-set +x
+set +xe
     if [ -e links ]; then rm links; fi
     if [ "$1" == s ]; then echo "$LINKZ" > links; fi
     if [ $COLLECTION ]; then LINKZ="$LINKS"; fi
@@ -45,7 +45,7 @@ set +x
         done
         if [ -e links2 ]; then mv links2 links; fi
     fi
-set -x
+set -xe
 }
 UPDATE_POSTS_DATABASE(){
     RUN(){
@@ -63,27 +63,25 @@ UPDATE_POSTS_DATABASE(){
         done
     }
     case "$1" in
-        -A) FILE=~/.turbodl/movie_list.txt; URL="https://turbodl.xyz/wp-json/wp/v2/posts?page"
+        -A) FILE=~/.turbodl/movie_list; URL="https://turbodl.xyz/wp-json/wp/v2/posts?page"
             printf ':: updating movie database...'; RUN; echo 'done!'
-            FILE=~/.turbodl/series_list.txt; URL="https://series.turbodl.xyz/wp-json/wp/v2/posts?page"
+            FILE=~/.turbodl/series_list; URL="https://series.turbodl.xyz/wp-json/wp/v2/posts?page"
             printf ':: updating series database...'; RUN; echo 'done!';;
-        -M) FILE=~/.turbodl/movie_list.txt; URL="https://turbodl.xyz/wp-json/wp/v2/posts?page"
+        -M) FILE=~/.turbodl/movie_list; URL="https://turbodl.xyz/wp-json/wp/v2/posts?page"
             printf ':: updating movie database...'; RUN; echo 'done!';;
-        -S) FILE=~/.turbodl/series_list.txt; URL="https://series.turbodl.xyz/wp-json/wp/v2/posts?page"
+        -S) FILE=~/.turbodl/series_list; URL="https://series.turbodl.xyz/wp-json/wp/v2/posts?page"
             printf ':: updating series database...'; RUN; echo 'done!';;
     esac
 }
 WRITE_TO_FILE(){
     if [[ $1 == S ]]; then
-        FOLDER='series'
-        #GET_SIZES s
+        FOLDER='series'; #GET_SIZES s
     elif [[ $1 == M ]]; then
-        FOLDER='movies'
-        GET_SIZES m
+        FOLDER='movies';GET_SIZES m
     else
         FOLDER=errors
     fi
-    if [ $1 == M ]; then LINKZ=$(cat links); fi
+    LINKZ=$(cat links)
     if [ "$KEY" ]; then
         echo -e "<p style=\"text-align: center;\">\\n$PLOT\\n\\n<center>Trailer:\\n<iframe src=\"https://www.youtube.com/embed/$KEY?modestbranding=1&showinfo=0&rel=0&iv_load_policy=3&color=white&controls=0\" width=\"500\" height=\"300\" frameborder=\"0\"></iframe></centre></p>\\n\\n<p style=\"text-align: center;\">IMDB Rating: $RATING\\nCast: $CAST\\nGenre: $GENRE</p>\\n\\n<p style=\"text-align: center;\">Download Links:\\n$LINKZ\\n</p>\\n\\nTags: $GENRE, $Y" > $FOLDER/"$OUTPUT".txt
     else
@@ -109,20 +107,19 @@ CROSS_CHECK(){
                     SAME=1 && export SAME; break
                 else
                     if [ "$USER" == '' ]; then
-set +x
+set +xe
                         DELETE_WP_POST
-set -x
+set -xe
                     fi
                     echo "deleted $OUTPUT"
                 fi
             else
                 if [ "$USER" == '' ]; then
-set +x
+set +xe
                     DELETE_WP_POST
-set -x
+set -xe
                 fi
-                sed -i "/$TITLE/d" $LIST
-                echo "deleted $OUTPUT"
+                sed -i "/$TITLE/d" $LIST; echo "deleted $OUTPUT"
             fi
             break
         else
@@ -148,24 +145,20 @@ set -x
 MULTI_FUNC(){
     output=$(grep ^'<a href=.*html.*title=.*</a>' <<< "$URL" | sed -e "s/'>.*//; s/.*title='//; s/<\/a>//")
     output2=$(grep ^'<a href=.*html.*title=.*</a>' <<< "$URL" | sed "s/'>.*//")
-    exec 3>&1 4>&2
-    trap 'exec 2>&4 1>&3' 0 1 2 3
-    exec 1>$1'logs.txt' 2>&1
+    exec 3>&1 4>&2; trap 'exec 2>&4 1>&3' 0 1 2 3; exec 1>$1'logs.txt' 2>&1
     while IFS= read -r "OUTPUT"; do
-        unset COLLECTION
-        if [ -e links ]; then rm links; fi
+        unset COLLECTION; if [ -e links ]; then rm links; fi
 set -xe
         echo -e "\\n$OUTPUT\\n-----------------------"
-        if [ "$2" ]; then
-            if ! grep -q "$OUTPUT" pattern; then continue 2; fi
+        if [ "$2" ] || [ -e pattern ]; then
+            if [ -e pattern ] && ! grep -q "$OUTPUT" pattern; then continue 2; fi
         fi
-#if [ "$OUTPUT" != "Hawaii Five-0" ]; then continue; fi
         if grep "$OUTPUT" blacklist; then echo "$OUTPUT blacklisted"; continue; fi
         if grep -i 'trailer' <<< "$OUTPUT"; then continue; fi
 set +xe
         SITE=$(curl $ARGS $(grep "$OUTPUT" <<< "$output2" | grep -o http.*html) || exit)
-set -xe
         LINKS=$(grep -oiE "(<span style=\"font-family.*http|<a href=).*(.*|S[0-9][0-9]E[0-9][0-9]).*(mkv|mp4|avi).*</a>" <<< "$SITE" | sed "s/.*<a/<a/; s/a>.*/a>/; s/CLICK HERE FOR SUBTITLES /Subtitles/; /Load more/d; /img/d")
+set -xe
         grep -qiE "(hd.*cm|HDCAM|CAM|HDTS).*(mkv|mp4|avi)" <<< "$LINKS" && continue
         YEAR=$(grep -woE '([0-9][0-9][0-9][0-9]$|[0-9][0-9][0-9][0-9])' <<< "$OUTPUT" || sed '0,/class=.*post-body/d; /CLICK ON.* LINK.* BELOW TO DOWNLOAD/,$d' <<< "$SITE" | grep -oE '(Release.*[0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9]<br />)' | grep -o '[0-9][0-9][0-9][0-9]' || echo 'null')
         if grep -q 'null' <<< "$YEAR"; then
@@ -180,11 +173,14 @@ set -xe
         fi
         if [ "$YEAR" -lt '2007' ]; then echo "$OUTPUT   -->   year less than 2007"; continue; fi
         NAME=$(sed -e 's/  $//; s/ $//; s/\./ /g; s/_/ /g; s/[ -.][0-9][0-9][0-9][0-9].*//; s/ ([0-9][0-9][0-9][0-9]).*//; s/ - Collection//; s/ Collection//; s/ (Tv-Series)//' <<< "$OUTPUT")
+        if grep -q "$OUTPUT=" whitelist; then
+            NAME=$(grep "$OUTPUT" whitelist | sed "s/.*$OUTPUT=//; s/;.*//g")
+        fi
         if [[ $1 == s ]]; then N='tv'; else N='movie'; fi
-if [ "$OUTPUT" == "Pirates of the Carribean - Collection" ]; then NAME='Pirates of the Caribbean'; fi
-if [ "$OUTPUT" == 'Magum P.I' ]; then NAME='Magum PI'; fi
         TMDB_API=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/search/$N?api_key=0dec8436bb1b7de2bbcb1920ac31111f&query=$(sed "s/ /%20/g" <<< "$NAME")&page=1&year=$YEAR" || exit)
-        if [ $(jq '.total_results' <<< "$TMDB_API") == 0 ]; then echo "$OUTPUT   -->   not found" >> $1'today.txt'; continue; fi
+        if [ $(jq '.total_results' <<< "$TMDB_API") == 0 ]; then
+            echo "$OUTPUT   -->   not found" >> $1'today.txt'; continue
+        fi
         if [[ $1 == s ]]; then F='first_air_date'; else F='release_date'; fi
         A=0
         while [ "$A" -lt "$(jq '.total_results' <<< $TMDB_API)" ]; do
@@ -252,11 +248,14 @@ if [ "$OUTPUT" == 'Magum P.I' ]; then NAME='Magum PI'; fi
         fi
         PLOT=$(jq -r '.Plot' <<< "$OMDB_API"); grep -q 'N/A' <<< "$PLOT" && PLOT="$OVERVIEW"
         if [[ $1 == s ]]; then PARSE; fi
+set +xe
         if [[ $1 == s ]]; then
-            Y=$(sed 's/–/, /' <<< $YEAR); LINKZ=$(cat links)
+            Y=$(sed 's/–/, /' <<< $YEAR)
+            LINKZ=$(cat links)
         else
             Y="$YEAR"; LINKZ="$LINKS"
         fi
+set -xe
         curl $ARGS "$POSTER" -o "$TITLE".jpg || if [ ! -e "$TITLE.jpg" ]; then
             echo "$OUTPUT   -->   img not found" >>  $1'today.txt'
             BLACKLIST; continue
@@ -286,9 +285,9 @@ if [ "$OUTPUT" == 'Magum P.I' ]; then NAME='Magum PI'; fi
             fi
         fi
         if [[ $1 == s ]]; then
-            LIST='series_list.txt'; SITE='series.turbodl.xyz'
+            LIST='series_list'; SITE='series.turbodl.xyz'
         else
-            LIST='movie_list.txt'; SITE='turbodl.xyz'
+            LIST='movie_list'; SITE='turbodl.xyz'
         fi
         if grep -owF "$TITLE" $LIST; then
             NUM=5; CROSS_CHECK $1
@@ -339,12 +338,11 @@ if [ "$OUTPUT" == 'Magum P.I' ]; then NAME='Magum PI'; fi
     echo "$(date)"
 }
 DIR=~/.turbodl; ARGS='--connect-timeout 5 --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -s'
-PIXELS=(480p 720p 1080p 2160p)
+PIXELS=(480p 720p 1080p 2160p); PARAMS=$#
 if [ ! -d "$DIR" ]; then
     mkdir -p "$DIR"/movies "$DIR"/series $DIR/errors; cd "$DIR"
 else
-    cd "$DIR"; mkdir -p movies series errors
-    rm *s/* *today.txt titles.txt *logs.txt links 2> /dev/null
+    cd "$DIR"; mkdir -p movies series errors; rm *s/* *txt links url pattern 2> /dev/null
 fi
 if [ "$USER" == '' ]; then
     cat ~/turbodl/whitelist > ~/.turbodl/whitelist; cat ~/turbodl/blacklist > ~/.turbodl/blacklist
@@ -352,52 +350,49 @@ elif [ "$USER" == 'persie' ]; then
     cat ~/git/turbodl/whitelist > ~/.turbodl/whitelist; cat ~/git/turbodl/blacklist > ~/.turbodl/blacklist
 fi
 case $1 in
-    '')
-        echo ':: no arguments, nothing to do';;
-    -g)
-        if [ "$USER" == '' ]; then (cd ~/turbodl/ && git pull); fi;;
-    -m)
-        URL=$(curl $ARGS "https://lightdlmovies.blogspot.com/search/label/MOVIES" || exit)
-        MULTI_FUNC m;;
-    -s)
-        URL=$(curl $ARGS "https://www.lightdl.xyz/search/label/TV%20SERIES" || exit)
-        MULTI_FUNC s;;
-    -a)
-        URL=$(curl $ARGS "https://lightdlmovies.blogspot.com/search/label/MOVIES" || exit)
-        MULTI_FUNC m
-set +xe
-        URL=$(curl $ARGS "https://www.lightdl.xyz/search/label/TV%20SERIES" || exit)
-        MULTI_FUNC s;;
-    -M|-S|-A)
-        UPDATE_POSTS_DATABASE "$1"
-        #if [ "$USER" == '' ]; then echo | mutt -s 'turbodl database updated' -- persie@turbodl.xyz; fi
-        ;;
-    -l)
-        PARAMS=$(($#-1))
-        if [ "$PARAMS" == 0 ]; then echo ':: no URLs'; exit; fi
+    ''|-g|-l)
+        if [ "$1" == -g ]; then
+            if [ "$USER" == '' ]; then (cd ~/turbodl/ && git pull); fi
+        elif [ "$1" == -l ]; then
+            shift
+            if [ "$PARAMS" == 1 ]; then echo ':: no URLs'; exit; fi
+            for POS_PARAM; do
+                if grep -q ^'%' <<< "$POS_PARAM"; then WORD=$(sed 's/%//' <<< "$POS_PARAM")
+                    grep -qiE '([a-z]|[0-9])' <<< "$WORD" && echo "$WORD" >> pattern || continue
+                elif grep -q 'http' <<< "$POS_PARAM"; then
+                    echo "$POS_PARAM" >> url
+                fi
+            done
+            exit
+            while IFS= read -r "OUTPUT"; do
+                if grep -qi movies <<< "$OUTPUT"; then
+                    URL=$(curl $ARGS "$OUTPUT" || exit); MULTI_FUNC m o
+                elif grep -qi SERIES <<< "$OUTPUT"; then
+                    URL=$(curl $ARGS "$OUTPUT" || exit); MULTI_FUNC s o
+                fi
+            done < url
+        else
+            echo ':: no arguments, nothing to do'
+        fi;;
+    -m|-s|-a|-M|-S|-A)
+        ONE=$1; shift
         for POS_PARAM; do
-            if [ "$POS_PARAM" == -l ]; then
-                continue
-            elif grep -q ^'%' <<< "$POS_PARAM"; then
-                WORD=$(sed 's/%//' <<< "$POS_PARAM")
+            if [ "$PARAMS" == 1 ]; then break; fi
+            if grep -q ^'%' <<< "$POS_PARAM"; then WORD=$(sed 's/%//' <<< "$POS_PARAM")
                 grep -qiE '([a-z]|[0-9])' <<< "$WORD" && echo "$WORD" >> pattern || continue
-            elif grep -q 'http' <<< "$POS_PARAM"; then
-                echo "$POS_PARAM" >> url
             fi
         done
-        while IFS= read -r "OUTPUT"; do
-            if grep -qi movies <<< "$OUTPUT"; then
-                URL=$(curl $ARGS "$OUTPUT" || exit); MULTI_FUNC m o
-            fi
-        done < url
-        if [ -e url ]; then rm url; fi; if [ -e pattern ]; then rm pattern; fi
-        ;;
-    *)
-        if grep -qi movies <<< "$1"; then
-            URL=$(curl $ARGS "$1" || exit); MULTI_FUNC m
-        elif grep -qi SERIES <<< "$1"; then
-            URL=$(curl $ARGS "$1" || exit); MULTI_FUNC s
+        if [ "$ONE" == -m ]; then
+            URL=$(curl $ARGS "https://lightdlmovies.blogspot.com/search/label/MOVIES" || exit); MULTI_FUNC m
+        elif [ "$ONE" == -s ]; then
+            URL=$(curl $ARGS "https://www.lightdl.xyz/search/label/TV%20SERIES" || exit); MULTI_FUNC s
+        elif [ "$ONE" == -a ]; then
+            URL=$(curl $ARGS "https://lightdlmovies.blogspot.com/search/label/MOVIES" || exit); MULTI_FUNC m
+set +xe
+            URL=$(curl $ARGS "https://www.lightdl.xyz/search/label/TV%20SERIES" || exit); MULTI_FUNC s
         else
-            echo ":: invalid: $1"
+            UPDATE_POSTS_DATABASE "$ONE"
         fi;;
+    *)
+        echo ":: invalid: $1";;
 esac
