updated

diff --git a/ultimate b/ultimate
--- a/ultimate
+++ b/ultimate
@@ -6,7 +6,7 @@ if [ ! -d "$DIR" ]; then
 else
     cd "$DIR"
     mkdir -p movies series errors
-    rm *s/* *today.txt titles.txt 2> /dev/null
+    rm *s/* *today.txt titles.txt *logs.txt 2> /dev/null
 fi
 
 PARSE(){
@@ -70,10 +70,10 @@ CROSS_CHECK(){
                     SAME=1 && export SAME; break
                 else
                     if [ "$USER" != persie ]; then
-                        set +x
+set +x
                         curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://turbodl.xyz/wp-json/wp/v2/posts/$(jq ".[$A].id" <<< "$WP_RESULTS")" 2> /dev/null
                         curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://turbodl.xyz/wp-json/wp/v2/media/$(jq ".[$A].featured_media" <<< "$WP_RESULTS")?force=true" 2> /dev/null
-                        set -x
+set -x
                     fi
                     if [[ $1 == s ]]; then
                         sed -i "s/$OUTPUT=.*/$OUTPUT=$(md5sum <<< "$LINKS2")/" MD5SUM
@@ -82,10 +82,10 @@ CROSS_CHECK(){
                 fi
             else
                 if [ "$USER" != persie ]; then
-                    set +x
+set +x
                     curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://turbodl.xyz/wp-json/wp/v2/posts/$(jq ".[$A].id" <<< "$WP_RESULTS")" 2> /dev/null
                     curl -s -X DELETE --user "looneytkp:Sgm4kv101413$" "https://turbodl.xyz/wp-json/wp/v2/media/$(jq ".[$A].featured_media" <<< "$WP_RESULTS")?force=true" 2> /dev/null
-                    set -x
+set -x
                 fi
 
                 if [[ $1 == s ]]; then
@@ -111,23 +111,29 @@ CROSS_CHECK(){
 MULTI_FUNC(){
     output=$(grep ^'<a href=.*html.*title=.*</a>' <<< "$URL" | sed -e "s/'>.*//; s/.*title='//; s/<\/a>//")
     output2=$(grep ^'<a href=.*html.*title=.*</a>' <<< "$URL" | sed "s/'>.*//")
-    if [ "$USER" != persie ]; then
+    #if [ "$USER" != persie ]; then
         exec 3>&1 4>&2
         trap 'exec 2>&4 1>&3' 0 1 2 3
-        exec 1>slogs.txt 2>&1
-    fi
+        exec 1>$1'logs.txt' 2>&1
+    #fi
     while IFS= read -r "OUTPUT"; do
-        set -xe
+set -xe
         echo -e "\\n$OUTPUT\\n-----------------------"
-#if [ "$OUTPUT" != "The Oval" ]; then continue; fi
+#if [ "$OUTPUT" != "Greys Anatomy" ]; then continue; fi
         if grep "$OUTPUT" blacklist; then echo "$OUTPUT blacklisted"; continue; fi
-        set +xe
+set +xe
         SITE=$(curl $ARGS $(grep "$OUTPUT" <<< "$output2" | grep -o http.*html))
-        set -xe
+set -xe
         LINKS=$(grep -oiE "(<span style=\"font-family.*http|<a href=).*(.*|S[0-9][0-9]E[0-9][0-9]).*(mkv|mp4|avi).*</a>" <<< "$SITE" | sed "s/.*<a/<a/; s/a>.*/a>/; s/CLICK HERE FOR SUBTITLES /Subtitles/; /Load more/d")
         grep -qiE "(hd.*cm|HDCAM|HDTS).*mkv" <<< "$LINKS" && continue
         YEAR=$(grep -woE '([0-9][0-9][0-9][0-9]$|[0-9][0-9][0-9][0-9])' <<< "$OUTPUT" || sed '0,/class=.*post-body/d; /CLICK ON.* LINK.* BELOW TO DOWNLOAD/,$d' <<< "$SITE" | grep -oE '(Release.*[0-9][0-9][0-9][0-9]|[0-9][0-9][0-9][0-9]<br />)' | grep -o '[0-9][0-9][0-9][0-9]' || echo 'null')
-        grep -q 'null' <<< "$YEAR" && echo "$OUTPUT   -->   year not found" >> $1'today.txt' && continue
+        if grep -q 'null' <<< "$YEAR"; then
+            if grep ^"$OUTPUT" whitelist; then
+                YEAR=$(grep "$OUTPUT" whitelist | sed 's/.*#//')
+            else
+                echo "$OUTPUT   -->   year not found" >> $1'today.txt' && continue
+            fi
+        fi
         NAME=$(sed -e 's/  $//; s/ $//; s/\./ /g; s/_/ /g; s/[ -.][0-9][0-9][0-9][0-9].*//; s/ ([0-9][0-9][0-9][0-9]).*//; s/ (Tv-Series)//' <<< "$OUTPUT")
         if [[ $1 == s ]]; then N='tv'; else N='movie'; fi
         TMDB_API=$(curl $ARGS -H "Accept: application/json" -H "Content-Type: application/json" "https://api.themoviedb.org/3/search/$N?api_key=0dec8436bb1b7de2bbcb1920ac31111f&query=$(sed "s/ /%20/g" <<< "$NAME")&page=1&year=$YEAR")
@@ -258,6 +264,7 @@ MULTI_FUNC(){
 if [ "$USER" != persie ]; then
     cat ~/turbodl/whitelist > ~/.turbodl/whitelist
     cat ~/turbodl/blacklist > ~/.turbodl/blacklist
+    cat ~/turbodl/urls > ~/.turbodl/urls
 fi
 case $1 in
     -m)
@@ -271,8 +278,7 @@ case $1 in
             done
         fi
         URL=$(curl $ARGS "https://lightdlmovies.blogspot.com/search/label/MOVIES" || exit)
-        MULTI_FUNC m
-        ;;
+        MULTI_FUNC m;;
     -s)
         if [ "$USER" != persie ]; then
             COUNT=1; COUNT1=0
@@ -284,6 +290,23 @@ case $1 in
             done
         fi
         URL=$(curl $ARGS "https://www.lightdl.xyz/search/label/TV%20SERIES" || exit)
-        MULTI_FUNC s
-        ;;
+        MULTI_FUNC s;;
+    -r)
+        while IFS= read -r "LNK"; do
+            if grep -q movies <<< "$LNK"; then
+                URL=$(curl $ARGS "$LNK" || exit); MULTI_FUNC m
+            elif grep -q SERIES <<< "$LINK"; then
+                URL=$(curl $ARGS "$LNK" || exit); MULTI_FUNC s
+            else
+                echo "invalid: $LNK"
+            fi
+        done < urls;;
+    *)
+        if grep -q movies <<< "$1"; then
+            URL=$(curl $ARGS "$1" || exit); MULTI_FUNC m
+        elif grep -q SERIES <<< "$1"; then
+            URL=$(curl $ARGS "$1" || exit); MULTI_FUNC s
+        else
+            echo "invalid $1"
+        fi;;
 esac
